/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models.containers;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.shell.apitest.ApiHelper;
import com.shell.apitest.models.MultiLocationMarkerV2;
import com.shell.apitest.models.SingleLocationMarkerV2;
import io.apimatic.core.annotations.TypeCombinator.TypeCombinatorCase;
import java.io.IOException;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Map;

/**
 * This is a container class for one-of types.
 */
@JsonDeserialize(using = LocationMarkerV2.LocationMarkerV2Deserializer.class)
public abstract class LocationMarkerV2 {
    
    /**
     * This is SingleLocationMarkerV2 case.
     * @param singleLocationMarkerV2 SingleLocationMarkerV2 value for singleLocationMarkerV2.
     * @return The SingleLocationMarkerV2Case object.
     */
    public static LocationMarkerV2 fromSingleLocationMarkerV2(
            SingleLocationMarkerV2 singleLocationMarkerV2) {
        return singleLocationMarkerV2 == null ? null : new SingleLocationMarkerV2Case(singleLocationMarkerV2);
    }

    /**
     * This is MultiLocationMarkerV2 case.
     * @param multiLocationMarkerV2 MultiLocationMarkerV2 value for multiLocationMarkerV2.
     * @return The MultiLocationMarkerV2Case object.
     */
    public static LocationMarkerV2 fromMultiLocationMarkerV2(
            MultiLocationMarkerV2 multiLocationMarkerV2) {
        return multiLocationMarkerV2 == null ? null : new MultiLocationMarkerV2Case(multiLocationMarkerV2);
    }

    /**
     * Method to match from the provided one-of cases.
     * @param <R> The type to return after applying callback.
     * @param cases The one-of type cases callback.
     * @return The one-of matched case.
     */
    public abstract <R> R match(Cases<R> cases);

    /**
     * This is interface for one-of cases.
     * @param <R> The type to return after applying callback.
     */
    public interface Cases<R> {
        R singleLocationMarkerV2(SingleLocationMarkerV2 singleLocationMarkerV2);

        R multiLocationMarkerV2(MultiLocationMarkerV2 multiLocationMarkerV2);
    }

    /**
     * This is a implementation class for SingleLocationMarkerV2Case.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "SingleLocationMarkerV2")
    private static class SingleLocationMarkerV2Case extends LocationMarkerV2 {

        @JsonValue
        private SingleLocationMarkerV2 singleLocationMarkerV2;

        SingleLocationMarkerV2Case(SingleLocationMarkerV2 singleLocationMarkerV2) {
            this.singleLocationMarkerV2 = singleLocationMarkerV2;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.singleLocationMarkerV2(this.singleLocationMarkerV2);
        }

        @JsonCreator
        private SingleLocationMarkerV2Case(JsonNode jsonNode) throws IOException {
            this.singleLocationMarkerV2 = ApiHelper.deserialize(jsonNode,
                SingleLocationMarkerV2.class);
        }

        @Override
        public String toString() {
            return singleLocationMarkerV2.toString();
        }
    }

    /**
     * This is a implementation class for MultiLocationMarkerV2Case.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "MultiLocationMarkerV2")
    private static class MultiLocationMarkerV2Case extends LocationMarkerV2 {

        @JsonValue
        private MultiLocationMarkerV2 multiLocationMarkerV2;

        MultiLocationMarkerV2Case(MultiLocationMarkerV2 multiLocationMarkerV2) {
            this.multiLocationMarkerV2 = multiLocationMarkerV2;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.multiLocationMarkerV2(this.multiLocationMarkerV2);
        }

        @JsonCreator
        private MultiLocationMarkerV2Case(JsonNode jsonNode) throws IOException {
            this.multiLocationMarkerV2 = ApiHelper.deserialize(jsonNode,
                MultiLocationMarkerV2.class);
        }

        @Override
        public String toString() {
            return multiLocationMarkerV2.toString();
        }
    }

    /**
     * This is a custom deserializer class for LocationMarkerV2.
     */
    protected static class LocationMarkerV2Deserializer
            extends JsonDeserializer<LocationMarkerV2> {

        private String discriminator = "markerType";
        private List<Map<String, Class<? extends LocationMarkerV2>>> registry =
                Arrays.asList(
                        Collections.singletonMap("SingleLocation", SingleLocationMarkerV2Case.class),
                        Collections.singletonMap("MultiLocation", MultiLocationMarkerV2Case.class));

        @Override
        public LocationMarkerV2 deserialize(JsonParser jp, DeserializationContext ctxt)
                throws IOException, JsonProcessingException {
            return ApiHelper.deserialize(jp, ctxt, discriminator, registry, null, true);
        }
    }

}
