/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.api.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.shell.api.models.BadRequestErrMsg;
import io.apimatic.coreinterfaces.http.Context;
import java.util.List;

/**
 * This is a model class for BadRequestException type.
 */
public class BadRequestException extends ApiException {
    private static final long serialVersionUID = 324316890950304113L;
    private String requestId;
    private String status;
    private List<BadRequestErrMsg> errors;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public BadRequestException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for RequestId.
     * requestId is unique identifier value that is attached to requests and messages that allow
     * reference to a particular transaction or event chain.
     * @return Returns the String
     */
    @JsonGetter("requestId")
    public String getRequestId() {
        return this.requestId;
    }

    /**
     * Setter for RequestId.
     * requestId is unique identifier value that is attached to requests and messages that allow
     * reference to a particular transaction or event chain.
     * @param requestId Value for String
     */
    @JsonSetter("requestId")
    private void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    /**
     * Getter for Status.
     * Status of the request
     * @return Returns the String
     */
    @JsonGetter("status")
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for Status.
     * Status of the request
     * @param status Value for String
     */
    @JsonSetter("status")
    private void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for Errors.
     * Exception details of the error
     * @return Returns the List of BadRequestErrMsg
     */
    @JsonGetter("errors")
    public List<BadRequestErrMsg> getErrors() {
        return this.errors;
    }

    /**
     * Setter for Errors.
     * Exception details of the error
     * @param errors Value for List of BadRequestErrMsg
     */
    @JsonSetter("errors")
    private void setErrors(List<BadRequestErrMsg> errors) {
        this.errors = errors;
    }
}
