/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Accessibility type.
 */
public class Accessibility {
    private AccessibilityStatusEnum status;
    private String remark;

    /**
     * Default constructor.
     */
    public Accessibility() {
    }

    /**
     * Initialization constructor.
     * @param  status  AccessibilityStatusEnum value for status.
     * @param  remark  String value for remark.
     */
    public Accessibility(
            AccessibilityStatusEnum status,
            String remark) {
        this.status = status;
        this.remark = remark;
    }

    /**
     * Getter for Status.
     * Accessibility Status
     * @return Returns the AccessibilityStatusEnum
     */
    @JsonGetter("status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AccessibilityStatusEnum getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * Accessibility Status
     * @param status Value for AccessibilityStatusEnum
     */
    @JsonSetter("status")
    public void setStatus(AccessibilityStatusEnum status) {
        this.status = status;
    }

    /**
     * Getter for Remark.
     * optional Arbitrary text about restrictions of the Location
     * @return Returns the String
     */
    @JsonGetter("remark")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getRemark() {
        return remark;
    }

    /**
     * Setter for Remark.
     * optional Arbitrary text about restrictions of the Location
     * @param remark Value for String
     */
    @JsonSetter("remark")
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * Converts this Accessibility into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Accessibility [" + "status=" + status + ", remark=" + remark + "]";
    }

    /**
     * Builds a new {@link Accessibility.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Accessibility.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .status(getStatus())
                .remark(getRemark());
        return builder;
    }

    /**
     * Class to build instances of {@link Accessibility}.
     */
    public static class Builder {
        private AccessibilityStatusEnum status;
        private String remark;



        /**
         * Setter for status.
         * @param  status  AccessibilityStatusEnum value for status.
         * @return Builder
         */
        public Builder status(AccessibilityStatusEnum status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for remark.
         * @param  remark  String value for remark.
         * @return Builder
         */
        public Builder remark(String remark) {
            this.remark = remark;
            return this;
        }

        /**
         * Builds a new {@link Accessibility} object using the set fields.
         * @return {@link Accessibility}
         */
        public Accessibility build() {
            return new Accessibility(status, remark);
        }
    }
}
