/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * ActiveResponse200JsonStatusEnum to be used.
 */
public enum ActiveResponse200JsonStatusEnum {
    SUCCESS,

    FAILED;


    private static TreeMap<String, ActiveResponse200JsonStatusEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        SUCCESS.value = "SUCCESS";
        FAILED.value = "FAILED";

        valueMap.put("SUCCESS", SUCCESS);
        valueMap.put("FAILED", FAILED);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static ActiveResponse200JsonStatusEnum constructFromString(String toConvert) throws IOException {
        ActiveResponse200JsonStatusEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static ActiveResponse200JsonStatusEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ActiveResponse200JsonStatusEnum values to list of string values.
     * @param toConvert The list of ActiveResponse200JsonStatusEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<ActiveResponse200JsonStatusEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (ActiveResponse200JsonStatusEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 