/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * DataRetrieveSessionCodeEnum to be used.
 */
public enum DataRetrieveSessionCodeEnum {
    INTERNALERROR,

    SERVICEUNAVAILABLE,

    CHARGETOKENNOTSUPPORTED,

    SESSIONINVALID,

    EVNOTCONNECTEDTOEVSE,

    EVSEINUSE,

    EVSEOUTOFSERVICE,

    EVSENOTFOUND,

    EVSENOTSUPPORTED;


    private static TreeMap<String, DataRetrieveSessionCodeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        INTERNALERROR.value = "InternalError";
        SERVICEUNAVAILABLE.value = "ServiceUnavailable";
        CHARGETOKENNOTSUPPORTED.value = "ChargeTokenNotSupported";
        SESSIONINVALID.value = "SessionInvalid";
        EVNOTCONNECTEDTOEVSE.value = "EvNotConnectedToEvse";
        EVSEINUSE.value = "EvseInUse";
        EVSEOUTOFSERVICE.value = "EvseOutOfService";
        EVSENOTFOUND.value = "EvseNotFound";
        EVSENOTSUPPORTED.value = "EvseNotSupported";

        valueMap.put("InternalError", INTERNALERROR);
        valueMap.put("ServiceUnavailable", SERVICEUNAVAILABLE);
        valueMap.put("ChargeTokenNotSupported", CHARGETOKENNOTSUPPORTED);
        valueMap.put("SessionInvalid", SESSIONINVALID);
        valueMap.put("EvNotConnectedToEvse", EVNOTCONNECTEDTOEVSE);
        valueMap.put("EvseInUse", EVSEINUSE);
        valueMap.put("EvseOutOfService", EVSEOUTOFSERVICE);
        valueMap.put("EvseNotFound", EVSENOTFOUND);
        valueMap.put("EvseNotSupported", EVSENOTSUPPORTED);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static DataRetrieveSessionCodeEnum constructFromString(String toConvert) throws IOException {
        DataRetrieveSessionCodeEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static DataRetrieveSessionCodeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of DataRetrieveSessionCodeEnum values to list of string values.
     * @param toConvert The list of DataRetrieveSessionCodeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<DataRetrieveSessionCodeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (DataRetrieveSessionCodeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 