/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * ElectricalPropertiesPowerTypeEnum to be used.
 */
public enum ElectricalPropertiesPowerTypeEnum {
    AC1PHASE,

    AC3PHASE,

    DC;


    private static TreeMap<String, ElectricalPropertiesPowerTypeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        AC1PHASE.value = "AC1Phase";
        AC3PHASE.value = "AC3Phase";
        DC.value = "DC";

        valueMap.put("AC1Phase", AC1PHASE);
        valueMap.put("AC3Phase", AC3PHASE);
        valueMap.put("DC", DC);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static ElectricalPropertiesPowerTypeEnum constructFromString(String toConvert) throws IOException {
        ElectricalPropertiesPowerTypeEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static ElectricalPropertiesPowerTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ElectricalPropertiesPowerTypeEnum values to list of string values.
     * @param toConvert The list of ElectricalPropertiesPowerTypeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<ElectricalPropertiesPowerTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (ElectricalPropertiesPowerTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 