/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * EnvEnum to be used.
 */
public enum EnvEnum {
    ENUM_APITESTSHELLCOM,

    ENUM_APISHELLCOM;


    private static TreeMap<String, EnvEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_APITESTSHELLCOM.value = "api-test.shell.com";
        ENUM_APISHELLCOM.value = "api.shell.com";

        valueMap.put("api-test.shell.com", ENUM_APITESTSHELLCOM);
        valueMap.put("api.shell.com", ENUM_APISHELLCOM);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static EnvEnum constructFromString(String toConvert) throws IOException {
        EnvEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static EnvEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of EnvEnum values to list of string values.
     * @param toConvert The list of EnvEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<EnvEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (EnvEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 