/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import java.util.UUID;

/**
 * This is a model class for InlineResponse202 type.
 */
public class InlineResponse202 {
    private UUID requestId;
    private InlineResponse202StatusEnum status;
    private List<InlineResponse202Data> data;

    /**
     * Default constructor.
     */
    public InlineResponse202() {
    }

    /**
     * Initialization constructor.
     * @param  requestId  UUID value for requestId.
     * @param  status  InlineResponse202StatusEnum value for status.
     * @param  data  List of InlineResponse202Data value for data.
     */
    public InlineResponse202(
            UUID requestId,
            InlineResponse202StatusEnum status,
            List<InlineResponse202Data> data) {
        this.requestId = requestId;
        this.status = status;
        this.data = data;
    }

    /**
     * Getter for RequestId.
     * Mandatory UUID (according to RFC 4122 standards) for requests and responses. This will be
     * played back in the response from the request.
     * @return Returns the UUID
     */
    @JsonGetter("RequestId")
    public UUID getRequestId() {
        return requestId;
    }

    /**
     * Setter for RequestId.
     * Mandatory UUID (according to RFC 4122 standards) for requests and responses. This will be
     * played back in the response from the request.
     * @param requestId Value for UUID
     */
    @JsonSetter("RequestId")
    public void setRequestId(UUID requestId) {
        this.requestId = requestId;
    }

    /**
     * Getter for Status.
     * Indicates overall status of the request
     * @return Returns the InlineResponse202StatusEnum
     */
    @JsonGetter("Status")
    public InlineResponse202StatusEnum getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * Indicates overall status of the request
     * @param status Value for InlineResponse202StatusEnum
     */
    @JsonSetter("Status")
    public void setStatus(InlineResponse202StatusEnum status) {
        this.status = status;
    }

    /**
     * Getter for Data.
     * @return Returns the List of InlineResponse202Data
     */
    @JsonGetter("Data")
    public List<InlineResponse202Data> getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for List of InlineResponse202Data
     */
    @JsonSetter("Data")
    public void setData(List<InlineResponse202Data> data) {
        this.data = data;
    }

    /**
     * Converts this InlineResponse202 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InlineResponse202 [" + "requestId=" + requestId + ", status=" + status + ", data="
                + data + "]";
    }

    /**
     * Builds a new {@link InlineResponse202.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InlineResponse202.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(requestId, status, data);
        return builder;
    }

    /**
     * Class to build instances of {@link InlineResponse202}.
     */
    public static class Builder {
        private UUID requestId;
        private InlineResponse202StatusEnum status;
        private List<InlineResponse202Data> data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  requestId  UUID value for requestId.
         * @param  status  InlineResponse202StatusEnum value for status.
         * @param  data  List of InlineResponse202Data value for data.
         */
        public Builder(UUID requestId, InlineResponse202StatusEnum status,
                List<InlineResponse202Data> data) {
            this.requestId = requestId;
            this.status = status;
            this.data = data;
        }

        /**
         * Setter for requestId.
         * @param  requestId  UUID value for requestId.
         * @return Builder
         */
        public Builder requestId(UUID requestId) {
            this.requestId = requestId;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  InlineResponse202StatusEnum value for status.
         * @return Builder
         */
        public Builder status(InlineResponse202StatusEnum status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for data.
         * @param  data  List of InlineResponse202Data value for data.
         * @return Builder
         */
        public Builder data(List<InlineResponse202Data> data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link InlineResponse202} object using the set fields.
         * @return {@link InlineResponse202}
         */
        public InlineResponse202 build() {
            return new InlineResponse202(requestId, status, data);
        }
    }
}
