/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PriceComponent type.
 */
public class PriceComponent {
    private TypeEnum type;
    private int stepSize;
    private double price;
    private double vat;

    /**
     * Default constructor.
     */
    public PriceComponent() {
    }

    /**
     * Initialization constructor.
     * @param  type  TypeEnum value for type.
     * @param  stepSize  int value for stepSize.
     * @param  price  double value for price.
     * @param  vat  double value for vat.
     */
    public PriceComponent(
            TypeEnum type,
            int stepSize,
            double price,
            double vat) {
        this.type = type;
        this.stepSize = stepSize;
        this.price = price;
        this.vat = vat;
    }

    /**
     * Getter for Type.
     * Type of the price component
     * @return Returns the TypeEnum
     */
    @JsonGetter("type")
    public TypeEnum getType() {
        return type;
    }

    /**
     * Setter for Type.
     * Type of the price component
     * @param type Value for TypeEnum
     */
    @JsonSetter("type")
    public void setType(TypeEnum type) {
        this.type = type;
    }

    /**
     * Getter for StepSize.
     * Step size in seconds for TIME-based components, in kWh for ENERGY-based components, or 1 for
     * FLAT components
     * @return Returns the int
     */
    @JsonGetter("stepSize")
    public int getStepSize() {
        return stepSize;
    }

    /**
     * Setter for StepSize.
     * Step size in seconds for TIME-based components, in kWh for ENERGY-based components, or 1 for
     * FLAT components
     * @param stepSize Value for int
     */
    @JsonSetter("stepSize")
    public void setStepSize(int stepSize) {
        this.stepSize = stepSize;
    }

    /**
     * Getter for Price.
     * Price per step in the specified currency for this price component
     * @return Returns the double
     */
    @JsonGetter("price")
    public double getPrice() {
        return price;
    }

    /**
     * Setter for Price.
     * Price per step in the specified currency for this price component
     * @param price Value for double
     */
    @JsonSetter("price")
    public void setPrice(double price) {
        this.price = price;
    }

    /**
     * Getter for Vat.
     * VAT percentage applicable to this price component
     * @return Returns the double
     */
    @JsonGetter("vat")
    public double getVat() {
        return vat;
    }

    /**
     * Setter for Vat.
     * VAT percentage applicable to this price component
     * @param vat Value for double
     */
    @JsonSetter("vat")
    public void setVat(double vat) {
        this.vat = vat;
    }

    /**
     * Converts this PriceComponent into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PriceComponent [" + "type=" + type + ", stepSize=" + stepSize + ", price=" + price
                + ", vat=" + vat + "]";
    }

    /**
     * Builds a new {@link PriceComponent.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PriceComponent.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(type, stepSize, price, vat);
        return builder;
    }

    /**
     * Class to build instances of {@link PriceComponent}.
     */
    public static class Builder {
        private TypeEnum type;
        private int stepSize;
        private double price;
        private double vat;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  type  TypeEnum value for type.
         * @param  stepSize  int value for stepSize.
         * @param  price  double value for price.
         * @param  vat  double value for vat.
         */
        public Builder(TypeEnum type, int stepSize, double price, double vat) {
            this.type = type;
            this.stepSize = stepSize;
            this.price = price;
            this.vat = vat;
        }

        /**
         * Setter for type.
         * @param  type  TypeEnum value for type.
         * @return Builder
         */
        public Builder type(TypeEnum type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for stepSize.
         * @param  stepSize  int value for stepSize.
         * @return Builder
         */
        public Builder stepSize(int stepSize) {
            this.stepSize = stepSize;
            return this;
        }

        /**
         * Setter for price.
         * @param  price  double value for price.
         * @return Builder
         */
        public Builder price(double price) {
            this.price = price;
            return this;
        }

        /**
         * Setter for vat.
         * @param  vat  double value for vat.
         * @return Builder
         */
        public Builder vat(double vat) {
            this.vat = vat;
            return this;
        }

        /**
         * Builds a new {@link PriceComponent} object using the set fields.
         * @return {@link PriceComponent}
         */
        public PriceComponent build() {
            return new PriceComponent(type, stepSize, price, vat);
        }
    }
}
