/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for ResponseError401AllOf1 type.
 */
public class ResponseError401AllOf1 {
    private List<ResponseError401AllOf1ErrorsItems> errors;

    /**
     * Default constructor.
     */
    public ResponseError401AllOf1() {
    }

    /**
     * Initialization constructor.
     * @param  errors  List of ResponseError401AllOf1ErrorsItems value for errors.
     */
    public ResponseError401AllOf1(
            List<ResponseError401AllOf1ErrorsItems> errors) {
        this.errors = errors;
    }

    /**
     * Getter for Errors.
     * Details of error(s) encountered
     * @return Returns the List of ResponseError401AllOf1ErrorsItems
     */
    @JsonGetter("Errors")
    public List<ResponseError401AllOf1ErrorsItems> getErrors() {
        return errors;
    }

    /**
     * Setter for Errors.
     * Details of error(s) encountered
     * @param errors Value for List of ResponseError401AllOf1ErrorsItems
     */
    @JsonSetter("Errors")
    public void setErrors(List<ResponseError401AllOf1ErrorsItems> errors) {
        this.errors = errors;
    }

    /**
     * Converts this ResponseError401AllOf1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ResponseError401AllOf1 [" + "errors=" + errors + "]";
    }

    /**
     * Builds a new {@link ResponseError401AllOf1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ResponseError401AllOf1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(errors);
        return builder;
    }

    /**
     * Class to build instances of {@link ResponseError401AllOf1}.
     */
    public static class Builder {
        private List<ResponseError401AllOf1ErrorsItems> errors;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  errors  List of ResponseError401AllOf1ErrorsItems value for errors.
         */
        public Builder(List<ResponseError401AllOf1ErrorsItems> errors) {
            this.errors = errors;
        }

        /**
         * Setter for errors.
         * @param  errors  List of ResponseError401AllOf1ErrorsItems value for errors.
         * @return Builder
         */
        public Builder errors(List<ResponseError401AllOf1ErrorsItems> errors) {
            this.errors = errors;
            return this;
        }

        /**
         * Builds a new {@link ResponseError401AllOf1} object using the set fields.
         * @return {@link ResponseError401AllOf1}
         */
        public ResponseError401AllOf1 build() {
            return new ResponseError401AllOf1(errors);
        }
    }
}
