/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for SearchByIdConnector type.
 */
public class SearchByIdConnector {
    private String uid;
    private String externalId;
    private ConnectorVOConnectorTypeEnum connectorType;
    private ElectricalPropertiesV2 electricalProperties;
    private List<TariffV2> tariffs;

    /**
     * Default constructor.
     */
    public SearchByIdConnector() {
    }

    /**
     * Initialization constructor.
     * @param  uid  String value for uid.
     * @param  externalId  String value for externalId.
     * @param  connectorType  ConnectorVOConnectorTypeEnum value for connectorType.
     * @param  electricalProperties  ElectricalPropertiesV2 value for electricalProperties.
     * @param  tariffs  List of TariffV2 value for tariffs.
     */
    public SearchByIdConnector(
            String uid,
            String externalId,
            ConnectorVOConnectorTypeEnum connectorType,
            ElectricalPropertiesV2 electricalProperties,
            List<TariffV2> tariffs) {
        this.uid = uid;
        this.externalId = externalId;
        this.connectorType = connectorType;
        this.electricalProperties = electricalProperties;
        this.tariffs = tariffs;
    }

    /**
     * Getter for Uid.
     * Internal identifier used to refer to this Connector
     * @return Returns the String
     */
    @JsonGetter("uid")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUid() {
        return uid;
    }

    /**
     * Setter for Uid.
     * Internal identifier used to refer to this Connector
     * @param uid Value for String
     */
    @JsonSetter("uid")
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * Getter for ExternalId.
     * Identifier of the Evse as given by the Operator, unique for the containing EVSE'
     * @return Returns the String
     */
    @JsonGetter("externalId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getExternalId() {
        return externalId;
    }

    /**
     * Setter for ExternalId.
     * Identifier of the Evse as given by the Operator, unique for the containing EVSE'
     * @param externalId Value for String
     */
    @JsonSetter("externalId")
    public void setExternalId(String externalId) {
        this.externalId = externalId;
    }

    /**
     * Getter for ConnectorType.
     * Type of the connector in the EVSE unit.
     * @return Returns the ConnectorVOConnectorTypeEnum
     */
    @JsonGetter("connectorType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ConnectorVOConnectorTypeEnum getConnectorType() {
        return connectorType;
    }

    /**
     * Setter for ConnectorType.
     * Type of the connector in the EVSE unit.
     * @param connectorType Value for ConnectorVOConnectorTypeEnum
     */
    @JsonSetter("connectorType")
    public void setConnectorType(ConnectorVOConnectorTypeEnum connectorType) {
        this.connectorType = connectorType;
    }

    /**
     * Getter for ElectricalProperties.
     * Electrical Properties of the Connector
     * @return Returns the ElectricalPropertiesV2
     */
    @JsonGetter("electricalProperties")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ElectricalPropertiesV2 getElectricalProperties() {
        return electricalProperties;
    }

    /**
     * Setter for ElectricalProperties.
     * Electrical Properties of the Connector
     * @param electricalProperties Value for ElectricalPropertiesV2
     */
    @JsonSetter("electricalProperties")
    public void setElectricalProperties(ElectricalPropertiesV2 electricalProperties) {
        this.electricalProperties = electricalProperties;
    }

    /**
     * Getter for Tariffs.
     * Tariffs applicable to this Connector
     * @return Returns the List of TariffV2
     */
    @JsonGetter("tariffs")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<TariffV2> getTariffs() {
        return tariffs;
    }

    /**
     * Setter for Tariffs.
     * Tariffs applicable to this Connector
     * @param tariffs Value for List of TariffV2
     */
    @JsonSetter("tariffs")
    public void setTariffs(List<TariffV2> tariffs) {
        this.tariffs = tariffs;
    }

    /**
     * Converts this SearchByIdConnector into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SearchByIdConnector [" + "uid=" + uid + ", externalId=" + externalId
                + ", connectorType=" + connectorType + ", electricalProperties="
                + electricalProperties + ", tariffs=" + tariffs + "]";
    }

    /**
     * Builds a new {@link SearchByIdConnector.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SearchByIdConnector.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .uid(getUid())
                .externalId(getExternalId())
                .connectorType(getConnectorType())
                .electricalProperties(getElectricalProperties())
                .tariffs(getTariffs());
        return builder;
    }

    /**
     * Class to build instances of {@link SearchByIdConnector}.
     */
    public static class Builder {
        private String uid;
        private String externalId;
        private ConnectorVOConnectorTypeEnum connectorType;
        private ElectricalPropertiesV2 electricalProperties;
        private List<TariffV2> tariffs;



        /**
         * Setter for uid.
         * @param  uid  String value for uid.
         * @return Builder
         */
        public Builder uid(String uid) {
            this.uid = uid;
            return this;
        }

        /**
         * Setter for externalId.
         * @param  externalId  String value for externalId.
         * @return Builder
         */
        public Builder externalId(String externalId) {
            this.externalId = externalId;
            return this;
        }

        /**
         * Setter for connectorType.
         * @param  connectorType  ConnectorVOConnectorTypeEnum value for connectorType.
         * @return Builder
         */
        public Builder connectorType(ConnectorVOConnectorTypeEnum connectorType) {
            this.connectorType = connectorType;
            return this;
        }

        /**
         * Setter for electricalProperties.
         * @param  electricalProperties  ElectricalPropertiesV2 value for electricalProperties.
         * @return Builder
         */
        public Builder electricalProperties(ElectricalPropertiesV2 electricalProperties) {
            this.electricalProperties = electricalProperties;
            return this;
        }

        /**
         * Setter for tariffs.
         * @param  tariffs  List of TariffV2 value for tariffs.
         * @return Builder
         */
        public Builder tariffs(List<TariffV2> tariffs) {
            this.tariffs = tariffs;
            return this;
        }

        /**
         * Builds a new {@link SearchByIdConnector} object using the set fields.
         * @return {@link SearchByIdConnector}
         */
        public SearchByIdConnector build() {
            return new SearchByIdConnector(uid, externalId, connectorType, electricalProperties,
                    tariffs);
        }
    }
}
