/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for SingleLocationMarkerV2 type.
 */
public class SingleLocationMarkerV2 {
    private SingleLocationMarkerStatusEnum status;
    private Coordinates coordinates;
    private Double evseCount;
    private Double maxPower;
    private Double locationCount;
    private String locationUid;
    private List<SingleLocationMarkerAuthorizationMethodsItemsEnum> authorizationMethods;
    private String operatorName;
    private String markerType;

    /**
     * Default constructor.
     */
    public SingleLocationMarkerV2() {
        markerType = "SingleLocation";
    }

    /**
     * Initialization constructor.
     * @param  markerType  String value for markerType.
     * @param  status  SingleLocationMarkerStatusEnum value for status.
     * @param  coordinates  Coordinates value for coordinates.
     * @param  evseCount  Double value for evseCount.
     * @param  maxPower  Double value for maxPower.
     * @param  locationCount  Double value for locationCount.
     * @param  locationUid  String value for locationUid.
     * @param  authorizationMethods  List of SingleLocationMarkerAuthorizationMethodsItemsEnum value
     *         for authorizationMethods.
     * @param  operatorName  String value for operatorName.
     */
    public SingleLocationMarkerV2(
            String markerType,
            SingleLocationMarkerStatusEnum status,
            Coordinates coordinates,
            Double evseCount,
            Double maxPower,
            Double locationCount,
            String locationUid,
            List<SingleLocationMarkerAuthorizationMethodsItemsEnum> authorizationMethods,
            String operatorName) {
        this.status = status;
        this.coordinates = coordinates;
        this.evseCount = evseCount;
        this.maxPower = maxPower;
        this.locationCount = locationCount;
        this.locationUid = locationUid;
        this.authorizationMethods = authorizationMethods;
        this.operatorName = operatorName;
        this.markerType = markerType;
    }

    /**
     * Initialization constructor.
     * @param  markerType  String value for markerType.
     */
    @JsonCreator
    protected SingleLocationMarkerV2(
            @JsonProperty("markerType") String markerType) {
        this(markerType, null, null, null, null, null, null, null, null);
    }

    /**
     * Getter for Status.
     * Minimum of all status values in the Marker, e.g. if at least one Evse in the Marker is
     * available, the value will be available
     * @return Returns the SingleLocationMarkerStatusEnum
     */
    @JsonGetter("status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public SingleLocationMarkerStatusEnum getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * Minimum of all status values in the Marker, e.g. if at least one Evse in the Marker is
     * available, the value will be available
     * @param status Value for SingleLocationMarkerStatusEnum
     */
    @JsonSetter("status")
    public void setStatus(SingleLocationMarkerStatusEnum status) {
        this.status = status;
    }

    /**
     * Getter for Coordinates.
     * Coordinates of the Shell Recharge Site Location
     * @return Returns the Coordinates
     */
    @JsonGetter("coordinates")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Coordinates getCoordinates() {
        return coordinates;
    }

    /**
     * Setter for Coordinates.
     * Coordinates of the Shell Recharge Site Location
     * @param coordinates Value for Coordinates
     */
    @JsonSetter("coordinates")
    public void setCoordinates(Coordinates coordinates) {
        this.coordinates = coordinates;
    }

    /**
     * Getter for EvseCount.
     * Total number of Evse units in Locations that this Marker represents
     * @return Returns the Double
     */
    @JsonGetter("evseCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getEvseCount() {
        return evseCount;
    }

    /**
     * Setter for EvseCount.
     * Total number of Evse units in Locations that this Marker represents
     * @param evseCount Value for Double
     */
    @JsonSetter("evseCount")
    public void setEvseCount(Double evseCount) {
        this.evseCount = evseCount;
    }

    /**
     * Getter for MaxPower.
     * Maximum power in kW across all locations grouped in this marker (disregarding availability)
     * @return Returns the Double
     */
    @JsonGetter("maxPower")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getMaxPower() {
        return maxPower;
    }

    /**
     * Setter for MaxPower.
     * Maximum power in kW across all locations grouped in this marker (disregarding availability)
     * @param maxPower Value for Double
     */
    @JsonSetter("maxPower")
    public void setMaxPower(Double maxPower) {
        this.maxPower = maxPower;
    }

    /**
     * Getter for LocationCount.
     * Number of Locations that this Marker represents in the given set of bounds
     * @return Returns the Double
     */
    @JsonGetter("locationCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getLocationCount() {
        return locationCount;
    }

    /**
     * Setter for LocationCount.
     * Number of Locations that this Marker represents in the given set of bounds
     * @param locationCount Value for Double
     */
    @JsonSetter("locationCount")
    public void setLocationCount(Double locationCount) {
        this.locationCount = locationCount;
    }

    /**
     * Getter for LocationUid.
     * Unique ID of the Location this Marker represents
     * @return Returns the String
     */
    @JsonGetter("locationUid")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLocationUid() {
        return locationUid;
    }

    /**
     * Setter for LocationUid.
     * Unique ID of the Location this Marker represents
     * @param locationUid Value for String
     */
    @JsonSetter("locationUid")
    public void setLocationUid(String locationUid) {
        this.locationUid = locationUid;
    }

    /**
     * Getter for AuthorizationMethods.
     * Methods that can be used to Authorize sessions on this EVSE
     * @return Returns the List of SingleLocationMarkerAuthorizationMethodsItemsEnum
     */
    @JsonGetter("authorizationMethods")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<SingleLocationMarkerAuthorizationMethodsItemsEnum> getAuthorizationMethods() {
        return authorizationMethods;
    }

    /**
     * Setter for AuthorizationMethods.
     * Methods that can be used to Authorize sessions on this EVSE
     * @param authorizationMethods Value for List of SingleLocationMarkerAuthorizationMethodsItemsEnum
     */
    @JsonSetter("authorizationMethods")
    public void setAuthorizationMethods(List<SingleLocationMarkerAuthorizationMethodsItemsEnum> authorizationMethods) {
        this.authorizationMethods = authorizationMethods;
    }

    /**
     * Getter for OperatorName.
     * Operator of this Shell Recharge Location
     * @return Returns the String
     */
    @JsonGetter("operatorName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * Setter for OperatorName.
     * Operator of this Shell Recharge Location
     * @param operatorName Value for String
     */
    @JsonSetter("operatorName")
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName;
    }

    /**
     * Getter for MarkerType.
     * Type of the Marker, in this case it will always be SingleLocation
     * @return Returns the String
     */
    @JsonGetter("markerType")
    public String getMarkerType() {
        return markerType;
    }

    /**
     * Setter for MarkerType.
     * Type of the Marker, in this case it will always be SingleLocation
     * @param markerType Value for String
     */
    @JsonSetter("markerType")
    private void setMarkerType(String markerType) {
        this.markerType = markerType;
    }

    /**
     * Converts this SingleLocationMarkerV2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SingleLocationMarkerV2 [" + "markerType=" + markerType + ", status=" + status
                + ", coordinates=" + coordinates + ", evseCount=" + evseCount + ", maxPower="
                + maxPower + ", locationCount=" + locationCount + ", locationUid=" + locationUid
                + ", authorizationMethods=" + authorizationMethods + ", operatorName="
                + operatorName + "]";
    }

    /**
     * Builds a new {@link SingleLocationMarkerV2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SingleLocationMarkerV2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(markerType)
                .status(getStatus())
                .coordinates(getCoordinates())
                .evseCount(getEvseCount())
                .maxPower(getMaxPower())
                .locationCount(getLocationCount())
                .locationUid(getLocationUid())
                .authorizationMethods(getAuthorizationMethods())
                .operatorName(getOperatorName());
        return builder;
    }

    /**
     * Class to build instances of {@link SingleLocationMarkerV2}.
     */
    public static class Builder {
        private String markerType = "SingleLocation";
        private SingleLocationMarkerStatusEnum status;
        private Coordinates coordinates;
        private Double evseCount;
        private Double maxPower;
        private Double locationCount;
        private String locationUid;
        private List<SingleLocationMarkerAuthorizationMethodsItemsEnum> authorizationMethods;
        private String operatorName;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  markerType  String value for markerType.
         */
        public Builder(String markerType) {
            this.markerType = markerType;
        }

        /**
         * Setter for markerType.
         * @param  markerType  String value for markerType.
         * @return Builder
         */
        public Builder markerType(String markerType) {
            this.markerType = markerType;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  SingleLocationMarkerStatusEnum value for status.
         * @return Builder
         */
        public Builder status(SingleLocationMarkerStatusEnum status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for coordinates.
         * @param  coordinates  Coordinates value for coordinates.
         * @return Builder
         */
        public Builder coordinates(Coordinates coordinates) {
            this.coordinates = coordinates;
            return this;
        }

        /**
         * Setter for evseCount.
         * @param  evseCount  Double value for evseCount.
         * @return Builder
         */
        public Builder evseCount(Double evseCount) {
            this.evseCount = evseCount;
            return this;
        }

        /**
         * Setter for maxPower.
         * @param  maxPower  Double value for maxPower.
         * @return Builder
         */
        public Builder maxPower(Double maxPower) {
            this.maxPower = maxPower;
            return this;
        }

        /**
         * Setter for locationCount.
         * @param  locationCount  Double value for locationCount.
         * @return Builder
         */
        public Builder locationCount(Double locationCount) {
            this.locationCount = locationCount;
            return this;
        }

        /**
         * Setter for locationUid.
         * @param  locationUid  String value for locationUid.
         * @return Builder
         */
        public Builder locationUid(String locationUid) {
            this.locationUid = locationUid;
            return this;
        }

        /**
         * Setter for authorizationMethods.
         * @param  authorizationMethods  List of SingleLocationMarkerAuthorizationMethodsItemsEnum
         *         value for authorizationMethods.
         * @return Builder
         */
        public Builder authorizationMethods(
                List<SingleLocationMarkerAuthorizationMethodsItemsEnum> authorizationMethods) {
            this.authorizationMethods = authorizationMethods;
            return this;
        }

        /**
         * Setter for operatorName.
         * @param  operatorName  String value for operatorName.
         * @return Builder
         */
        public Builder operatorName(String operatorName) {
            this.operatorName = operatorName;
            return this;
        }

        /**
         * Builds a new {@link SingleLocationMarkerV2} object using the set fields.
         * @return {@link SingleLocationMarkerV2}
         */
        public SingleLocationMarkerV2 build() {
            return new SingleLocationMarkerV2(markerType, status, coordinates, evseCount, maxPower,
                    locationCount, locationUid, authorizationMethods, operatorName);
        }
    }
}
