/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for SuccessResponse type.
 */
public class SuccessResponse {
    private String requestId;
    private ResponseBaseStatusEnum status;

    /**
     * Default constructor.
     */
    public SuccessResponse() {
    }

    /**
     * Initialization constructor.
     * @param  requestId  String value for requestId.
     * @param  status  ResponseBaseStatusEnum value for status.
     */
    public SuccessResponse(
            String requestId,
            ResponseBaseStatusEnum status) {
        this.requestId = requestId;
        this.status = status;
    }

    /**
     * Getter for RequestId.
     * A unique request id in GUID format. The value is written to the Shell API Platform audit log
     * for end to end traceability of a request.
     * @return Returns the String
     */
    @JsonGetter("RequestId")
    public String getRequestId() {
        return requestId;
    }

    /**
     * Setter for RequestId.
     * A unique request id in GUID format. The value is written to the Shell API Platform audit log
     * for end to end traceability of a request.
     * @param requestId Value for String
     */
    @JsonSetter("RequestId")
    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    /**
     * Getter for Status.
     * Indicates overall status of the request
     * @return Returns the ResponseBaseStatusEnum
     */
    @JsonGetter("Status")
    public ResponseBaseStatusEnum getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * Indicates overall status of the request
     * @param status Value for ResponseBaseStatusEnum
     */
    @JsonSetter("Status")
    public void setStatus(ResponseBaseStatusEnum status) {
        this.status = status;
    }

    /**
     * Converts this SuccessResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SuccessResponse [" + "requestId=" + requestId + ", status=" + status + "]";
    }

    /**
     * Builds a new {@link SuccessResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SuccessResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(requestId, status);
        return builder;
    }

    /**
     * Class to build instances of {@link SuccessResponse}.
     */
    public static class Builder {
        private String requestId;
        private ResponseBaseStatusEnum status;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  requestId  String value for requestId.
         * @param  status  ResponseBaseStatusEnum value for status.
         */
        public Builder(String requestId, ResponseBaseStatusEnum status) {
            this.requestId = requestId;
            this.status = status;
        }

        /**
         * Setter for requestId.
         * @param  requestId  String value for requestId.
         * @return Builder
         */
        public Builder requestId(String requestId) {
            this.requestId = requestId;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  ResponseBaseStatusEnum value for status.
         * @return Builder
         */
        public Builder status(ResponseBaseStatusEnum status) {
            this.status = status;
            return this;
        }

        /**
         * Builds a new {@link SuccessResponse} object using the set fields.
         * @return {@link SuccessResponse}
         */
        public SuccessResponse build() {
            return new SuccessResponse(requestId, status);
        }
    }
}
