/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.shell.apitest.DateTimeHelper;
import java.time.LocalDateTime;
import java.util.List;

/**
 * This is a model class for TariffV2 type.
 */
public class TariffV2 {
    private String tariffId;
    private TariffTypeEnum tariffType;
    private PowerRange powerRange;
    private String internalId;
    private String operatorId;
    private String providerId;
    private String currency;
    private List<TariffAltText> tariffAltText;
    private double minPrice;
    private double maxPrice;
    private List<TariffElement> elements;
    private LocalDateTime startDateTime;
    private LocalDateTime endDateTime;
    private LocalDateTime lastUpdated;
    private String createdBy;

    /**
     * Default constructor.
     */
    public TariffV2() {
    }

    /**
     * Initialization constructor.
     * @param  tariffId  String value for tariffId.
     * @param  tariffType  TariffTypeEnum value for tariffType.
     * @param  powerRange  PowerRange value for powerRange.
     * @param  internalId  String value for internalId.
     * @param  operatorId  String value for operatorId.
     * @param  providerId  String value for providerId.
     * @param  currency  String value for currency.
     * @param  tariffAltText  List of TariffAltText value for tariffAltText.
     * @param  minPrice  double value for minPrice.
     * @param  maxPrice  double value for maxPrice.
     * @param  elements  List of TariffElement value for elements.
     * @param  startDateTime  LocalDateTime value for startDateTime.
     * @param  endDateTime  LocalDateTime value for endDateTime.
     * @param  lastUpdated  LocalDateTime value for lastUpdated.
     * @param  createdBy  String value for createdBy.
     */
    public TariffV2(
            String tariffId,
            TariffTypeEnum tariffType,
            PowerRange powerRange,
            String internalId,
            String operatorId,
            String providerId,
            String currency,
            List<TariffAltText> tariffAltText,
            double minPrice,
            double maxPrice,
            List<TariffElement> elements,
            LocalDateTime startDateTime,
            LocalDateTime endDateTime,
            LocalDateTime lastUpdated,
            String createdBy) {
        this.tariffId = tariffId;
        this.tariffType = tariffType;
        this.powerRange = powerRange;
        this.internalId = internalId;
        this.operatorId = operatorId;
        this.providerId = providerId;
        this.currency = currency;
        this.tariffAltText = tariffAltText;
        this.minPrice = minPrice;
        this.maxPrice = maxPrice;
        this.elements = elements;
        this.startDateTime = startDateTime;
        this.endDateTime = endDateTime;
        this.lastUpdated = lastUpdated;
        this.createdBy = createdBy;
    }

    /**
     * Getter for TariffId.
     * Unique identifier for the tariff
     * @return Returns the String
     */
    @JsonGetter("tariffId")
    public String getTariffId() {
        return tariffId;
    }

    /**
     * Setter for TariffId.
     * Unique identifier for the tariff
     * @param tariffId Value for String
     */
    @JsonSetter("tariffId")
    public void setTariffId(String tariffId) {
        this.tariffId = tariffId;
    }

    /**
     * Getter for TariffType.
     * Tariff type classification
     * @return Returns the TariffTypeEnum
     */
    @JsonGetter("tariffType")
    public TariffTypeEnum getTariffType() {
        return tariffType;
    }

    /**
     * Setter for TariffType.
     * Tariff type classification
     * @param tariffType Value for TariffTypeEnum
     */
    @JsonSetter("tariffType")
    public void setTariffType(TariffTypeEnum tariffType) {
        this.tariffType = tariffType;
    }

    /**
     * Getter for PowerRange.
     * @return Returns the PowerRange
     */
    @JsonGetter("powerRange")
    public PowerRange getPowerRange() {
        return powerRange;
    }

    /**
     * Setter for PowerRange.
     * @param powerRange Value for PowerRange
     */
    @JsonSetter("powerRange")
    public void setPowerRange(PowerRange powerRange) {
        this.powerRange = powerRange;
    }

    /**
     * Getter for InternalId.
     * Internal identifier used by the platform
     * @return Returns the String
     */
    @JsonGetter("internalId")
    public String getInternalId() {
        return internalId;
    }

    /**
     * Setter for InternalId.
     * Internal identifier used by the platform
     * @param internalId Value for String
     */
    @JsonSetter("internalId")
    public void setInternalId(String internalId) {
        this.internalId = internalId;
    }

    /**
     * Getter for OperatorId.
     * Unique identifier of the operator
     * @return Returns the String
     */
    @JsonGetter("operatorId")
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * Setter for OperatorId.
     * Unique identifier of the operator
     * @param operatorId Value for String
     */
    @JsonSetter("operatorId")
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * Getter for ProviderId.
     * Unique identifier of the provider
     * @return Returns the String
     */
    @JsonGetter("providerId")
    public String getProviderId() {
        return providerId;
    }

    /**
     * Setter for ProviderId.
     * Unique identifier of the provider
     * @param providerId Value for String
     */
    @JsonSetter("providerId")
    public void setProviderId(String providerId) {
        this.providerId = providerId;
    }

    /**
     * Getter for Currency.
     * ISO 4217 Currency Code
     * @return Returns the String
     */
    @JsonGetter("currency")
    public String getCurrency() {
        return currency;
    }

    /**
     * Setter for Currency.
     * ISO 4217 Currency Code
     * @param currency Value for String
     */
    @JsonSetter("currency")
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * Getter for TariffAltText.
     * @return Returns the List of TariffAltText
     */
    @JsonGetter("tariffAltText")
    public List<TariffAltText> getTariffAltText() {
        return tariffAltText;
    }

    /**
     * Setter for TariffAltText.
     * @param tariffAltText Value for List of TariffAltText
     */
    @JsonSetter("tariffAltText")
    public void setTariffAltText(List<TariffAltText> tariffAltText) {
        this.tariffAltText = tariffAltText;
    }

    /**
     * Getter for MinPrice.
     * @return Returns the double
     */
    @JsonGetter("minPrice")
    public double getMinPrice() {
        return minPrice;
    }

    /**
     * Setter for MinPrice.
     * @param minPrice Value for double
     */
    @JsonSetter("minPrice")
    public void setMinPrice(double minPrice) {
        this.minPrice = minPrice;
    }

    /**
     * Getter for MaxPrice.
     * @return Returns the double
     */
    @JsonGetter("maxPrice")
    public double getMaxPrice() {
        return maxPrice;
    }

    /**
     * Setter for MaxPrice.
     * @param maxPrice Value for double
     */
    @JsonSetter("maxPrice")
    public void setMaxPrice(double maxPrice) {
        this.maxPrice = maxPrice;
    }

    /**
     * Getter for Elements.
     * @return Returns the List of TariffElement
     */
    @JsonGetter("elements")
    public List<TariffElement> getElements() {
        return elements;
    }

    /**
     * Setter for Elements.
     * @param elements Value for List of TariffElement
     */
    @JsonSetter("elements")
    public void setElements(List<TariffElement> elements) {
        this.elements = elements;
    }

    /**
     * Getter for StartDateTime.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("startDateTime")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getStartDateTime() {
        return startDateTime;
    }

    /**
     * Setter for StartDateTime.
     * @param startDateTime Value for LocalDateTime
     */
    @JsonSetter("startDateTime")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setStartDateTime(LocalDateTime startDateTime) {
        this.startDateTime = startDateTime;
    }

    /**
     * Getter for EndDateTime.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("endDateTime")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getEndDateTime() {
        return endDateTime;
    }

    /**
     * Setter for EndDateTime.
     * @param endDateTime Value for LocalDateTime
     */
    @JsonSetter("endDateTime")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setEndDateTime(LocalDateTime endDateTime) {
        this.endDateTime = endDateTime;
    }

    /**
     * Getter for LastUpdated.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("lastUpdated")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getLastUpdated() {
        return lastUpdated;
    }

    /**
     * Setter for LastUpdated.
     * @param lastUpdated Value for LocalDateTime
     */
    @JsonSetter("lastUpdated")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setLastUpdated(LocalDateTime lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * Getter for CreatedBy.
     * Identifier of the actor who created the tariff
     * @return Returns the String
     */
    @JsonGetter("createdBy")
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * Setter for CreatedBy.
     * Identifier of the actor who created the tariff
     * @param createdBy Value for String
     */
    @JsonSetter("createdBy")
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Converts this TariffV2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TariffV2 [" + "tariffId=" + tariffId + ", tariffType=" + tariffType
                + ", powerRange=" + powerRange + ", internalId=" + internalId + ", operatorId="
                + operatorId + ", providerId=" + providerId + ", currency=" + currency
                + ", tariffAltText=" + tariffAltText + ", minPrice=" + minPrice + ", maxPrice="
                + maxPrice + ", elements=" + elements + ", startDateTime=" + startDateTime
                + ", endDateTime=" + endDateTime + ", lastUpdated=" + lastUpdated + ", createdBy="
                + createdBy + "]";
    }

    /**
     * Builds a new {@link TariffV2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TariffV2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(tariffId, tariffType, powerRange, internalId, operatorId,
                providerId, currency, tariffAltText, minPrice, maxPrice, elements, startDateTime,
                endDateTime, lastUpdated, createdBy);
        return builder;
    }

    /**
     * Class to build instances of {@link TariffV2}.
     */
    public static class Builder {
        private String tariffId;
        private TariffTypeEnum tariffType;
        private PowerRange powerRange;
        private String internalId;
        private String operatorId;
        private String providerId;
        private String currency;
        private List<TariffAltText> tariffAltText;
        private double minPrice;
        private double maxPrice;
        private List<TariffElement> elements;
        private LocalDateTime startDateTime;
        private LocalDateTime endDateTime;
        private LocalDateTime lastUpdated;
        private String createdBy;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  tariffId  String value for tariffId.
         * @param  tariffType  TariffTypeEnum value for tariffType.
         * @param  powerRange  PowerRange value for powerRange.
         * @param  internalId  String value for internalId.
         * @param  operatorId  String value for operatorId.
         * @param  providerId  String value for providerId.
         * @param  currency  String value for currency.
         * @param  tariffAltText  List of TariffAltText value for tariffAltText.
         * @param  minPrice  double value for minPrice.
         * @param  maxPrice  double value for maxPrice.
         * @param  elements  List of TariffElement value for elements.
         * @param  startDateTime  LocalDateTime value for startDateTime.
         * @param  endDateTime  LocalDateTime value for endDateTime.
         * @param  lastUpdated  LocalDateTime value for lastUpdated.
         * @param  createdBy  String value for createdBy.
         */
        public Builder(String tariffId, TariffTypeEnum tariffType, PowerRange powerRange,
                String internalId, String operatorId, String providerId, String currency,
                List<TariffAltText> tariffAltText, double minPrice, double maxPrice,
                List<TariffElement> elements, LocalDateTime startDateTime,
                LocalDateTime endDateTime, LocalDateTime lastUpdated, String createdBy) {
            this.tariffId = tariffId;
            this.tariffType = tariffType;
            this.powerRange = powerRange;
            this.internalId = internalId;
            this.operatorId = operatorId;
            this.providerId = providerId;
            this.currency = currency;
            this.tariffAltText = tariffAltText;
            this.minPrice = minPrice;
            this.maxPrice = maxPrice;
            this.elements = elements;
            this.startDateTime = startDateTime;
            this.endDateTime = endDateTime;
            this.lastUpdated = lastUpdated;
            this.createdBy = createdBy;
        }

        /**
         * Setter for tariffId.
         * @param  tariffId  String value for tariffId.
         * @return Builder
         */
        public Builder tariffId(String tariffId) {
            this.tariffId = tariffId;
            return this;
        }

        /**
         * Setter for tariffType.
         * @param  tariffType  TariffTypeEnum value for tariffType.
         * @return Builder
         */
        public Builder tariffType(TariffTypeEnum tariffType) {
            this.tariffType = tariffType;
            return this;
        }

        /**
         * Setter for powerRange.
         * @param  powerRange  PowerRange value for powerRange.
         * @return Builder
         */
        public Builder powerRange(PowerRange powerRange) {
            this.powerRange = powerRange;
            return this;
        }

        /**
         * Setter for internalId.
         * @param  internalId  String value for internalId.
         * @return Builder
         */
        public Builder internalId(String internalId) {
            this.internalId = internalId;
            return this;
        }

        /**
         * Setter for operatorId.
         * @param  operatorId  String value for operatorId.
         * @return Builder
         */
        public Builder operatorId(String operatorId) {
            this.operatorId = operatorId;
            return this;
        }

        /**
         * Setter for providerId.
         * @param  providerId  String value for providerId.
         * @return Builder
         */
        public Builder providerId(String providerId) {
            this.providerId = providerId;
            return this;
        }

        /**
         * Setter for currency.
         * @param  currency  String value for currency.
         * @return Builder
         */
        public Builder currency(String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * Setter for tariffAltText.
         * @param  tariffAltText  List of TariffAltText value for tariffAltText.
         * @return Builder
         */
        public Builder tariffAltText(List<TariffAltText> tariffAltText) {
            this.tariffAltText = tariffAltText;
            return this;
        }

        /**
         * Setter for minPrice.
         * @param  minPrice  double value for minPrice.
         * @return Builder
         */
        public Builder minPrice(double minPrice) {
            this.minPrice = minPrice;
            return this;
        }

        /**
         * Setter for maxPrice.
         * @param  maxPrice  double value for maxPrice.
         * @return Builder
         */
        public Builder maxPrice(double maxPrice) {
            this.maxPrice = maxPrice;
            return this;
        }

        /**
         * Setter for elements.
         * @param  elements  List of TariffElement value for elements.
         * @return Builder
         */
        public Builder elements(List<TariffElement> elements) {
            this.elements = elements;
            return this;
        }

        /**
         * Setter for startDateTime.
         * @param  startDateTime  LocalDateTime value for startDateTime.
         * @return Builder
         */
        public Builder startDateTime(LocalDateTime startDateTime) {
            this.startDateTime = startDateTime;
            return this;
        }

        /**
         * Setter for endDateTime.
         * @param  endDateTime  LocalDateTime value for endDateTime.
         * @return Builder
         */
        public Builder endDateTime(LocalDateTime endDateTime) {
            this.endDateTime = endDateTime;
            return this;
        }

        /**
         * Setter for lastUpdated.
         * @param  lastUpdated  LocalDateTime value for lastUpdated.
         * @return Builder
         */
        public Builder lastUpdated(LocalDateTime lastUpdated) {
            this.lastUpdated = lastUpdated;
            return this;
        }

        /**
         * Setter for createdBy.
         * @param  createdBy  String value for createdBy.
         * @return Builder
         */
        public Builder createdBy(String createdBy) {
            this.createdBy = createdBy;
            return this;
        }

        /**
         * Builds a new {@link TariffV2} object using the set fields.
         * @return {@link TariffV2}
         */
        public TariffV2 build() {
            return new TariffV2(tariffId, tariffType, powerRange, internalId, operatorId,
                    providerId, currency, tariffAltText, minPrice, maxPrice, elements,
                    startDateTime, endDateTime, lastUpdated, createdBy);
        }
    }
}
