/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for AccessibilityV2 type.
 */
public class AccessibilityV2 {
    private AccessibilityStatusEnum status;

    /**
     * Default constructor.
     */
    public AccessibilityV2() {
    }

    /**
     * Initialization constructor.
     * @param  status  AccessibilityStatusEnum value for status.
     */
    public AccessibilityV2(
            AccessibilityStatusEnum status) {
        this.status = status;
    }

    /**
     * Getter for Status.
     * Accessibility Status
     * @return Returns the AccessibilityStatusEnum
     */
    @JsonGetter("status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AccessibilityStatusEnum getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * Accessibility Status
     * @param status Value for AccessibilityStatusEnum
     */
    @JsonSetter("status")
    public void setStatus(AccessibilityStatusEnum status) {
        this.status = status;
    }

    /**
     * Converts this AccessibilityV2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AccessibilityV2 [" + "status=" + status + "]";
    }

    /**
     * Builds a new {@link AccessibilityV2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AccessibilityV2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .status(getStatus());
        return builder;
    }

    /**
     * Class to build instances of {@link AccessibilityV2}.
     */
    public static class Builder {
        private AccessibilityStatusEnum status;



        /**
         * Setter for status.
         * @param  status  AccessibilityStatusEnum value for status.
         * @return Builder
         */
        public Builder status(AccessibilityStatusEnum status) {
            this.status = status;
            return this;
        }

        /**
         * Builds a new {@link AccessibilityV2} object using the set fields.
         * @return {@link AccessibilityV2}
         */
        public AccessibilityV2 build() {
            return new AccessibilityV2(status);
        }
    }
}
