/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ChargeRetrieveState type.
 */
public class ChargeRetrieveState {
    private String status;
    private ChargeError error;

    /**
     * Default constructor.
     */
    public ChargeRetrieveState() {
    }

    /**
     * Initialization constructor.
     * @param  status  String value for status.
     * @param  error  ChargeError value for error.
     */
    public ChargeRetrieveState(
            String status,
            ChargeError error) {
        this.status = status;
        this.error = error;
    }

    /**
     * Getter for Status.
     * Describes the session state started, stopped, start-requested, stop-requested,
     * failed-to-start, failed-to-stop
     * @return Returns the String
     */
    @JsonGetter("status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * Describes the session state started, stopped, start-requested, stop-requested,
     * failed-to-start, failed-to-stop
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for Error.
     * @return Returns the ChargeError
     */
    @JsonGetter("error")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ChargeError getError() {
        return error;
    }

    /**
     * Setter for Error.
     * @param error Value for ChargeError
     */
    @JsonSetter("error")
    public void setError(ChargeError error) {
        this.error = error;
    }

    /**
     * Converts this ChargeRetrieveState into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ChargeRetrieveState [" + "status=" + status + ", error=" + error + "]";
    }

    /**
     * Builds a new {@link ChargeRetrieveState.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ChargeRetrieveState.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .status(getStatus())
                .error(getError());
        return builder;
    }

    /**
     * Class to build instances of {@link ChargeRetrieveState}.
     */
    public static class Builder {
        private String status;
        private ChargeError error;



        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for error.
         * @param  error  ChargeError value for error.
         * @return Builder
         */
        public Builder error(ChargeError error) {
            this.error = error;
            return this;
        }

        /**
         * Builds a new {@link ChargeRetrieveState} object using the set fields.
         * @return {@link ChargeRetrieveState}
         */
        public ChargeRetrieveState build() {
            return new ChargeRetrieveState(status, error);
        }
    }
}
