/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ConnectorV2 type.
 */
public class ConnectorV2 {
    private String uid;
    private String externalId;
    private ConnectorVOConnectorTypeEnum connectorType;
    private ElectricalPropertiesV2 electricalProperties;

    /**
     * Default constructor.
     */
    public ConnectorV2() {
    }

    /**
     * Initialization constructor.
     * @param  uid  String value for uid.
     * @param  externalId  String value for externalId.
     * @param  connectorType  ConnectorVOConnectorTypeEnum value for connectorType.
     * @param  electricalProperties  ElectricalPropertiesV2 value for electricalProperties.
     */
    public ConnectorV2(
            String uid,
            String externalId,
            ConnectorVOConnectorTypeEnum connectorType,
            ElectricalPropertiesV2 electricalProperties) {
        this.uid = uid;
        this.externalId = externalId;
        this.connectorType = connectorType;
        this.electricalProperties = electricalProperties;
    }

    /**
     * Getter for Uid.
     * Internal identifier used to refer to this Connector
     * @return Returns the String
     */
    @JsonGetter("uid")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUid() {
        return uid;
    }

    /**
     * Setter for Uid.
     * Internal identifier used to refer to this Connector
     * @param uid Value for String
     */
    @JsonSetter("uid")
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * Getter for ExternalId.
     * Identifier of the Evse as given by the Operator, unique for the containing EVSE'
     * @return Returns the String
     */
    @JsonGetter("externalId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getExternalId() {
        return externalId;
    }

    /**
     * Setter for ExternalId.
     * Identifier of the Evse as given by the Operator, unique for the containing EVSE'
     * @param externalId Value for String
     */
    @JsonSetter("externalId")
    public void setExternalId(String externalId) {
        this.externalId = externalId;
    }

    /**
     * Getter for ConnectorType.
     * Type of the connector in the EVSE unit.
     * @return Returns the ConnectorVOConnectorTypeEnum
     */
    @JsonGetter("connectorType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ConnectorVOConnectorTypeEnum getConnectorType() {
        return connectorType;
    }

    /**
     * Setter for ConnectorType.
     * Type of the connector in the EVSE unit.
     * @param connectorType Value for ConnectorVOConnectorTypeEnum
     */
    @JsonSetter("connectorType")
    public void setConnectorType(ConnectorVOConnectorTypeEnum connectorType) {
        this.connectorType = connectorType;
    }

    /**
     * Getter for ElectricalProperties.
     * Electrical Properties of the Connector
     * @return Returns the ElectricalPropertiesV2
     */
    @JsonGetter("electricalProperties")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ElectricalPropertiesV2 getElectricalProperties() {
        return electricalProperties;
    }

    /**
     * Setter for ElectricalProperties.
     * Electrical Properties of the Connector
     * @param electricalProperties Value for ElectricalPropertiesV2
     */
    @JsonSetter("electricalProperties")
    public void setElectricalProperties(ElectricalPropertiesV2 electricalProperties) {
        this.electricalProperties = electricalProperties;
    }

    /**
     * Converts this ConnectorV2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ConnectorV2 [" + "uid=" + uid + ", externalId=" + externalId + ", connectorType="
                + connectorType + ", electricalProperties=" + electricalProperties + "]";
    }

    /**
     * Builds a new {@link ConnectorV2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ConnectorV2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .uid(getUid())
                .externalId(getExternalId())
                .connectorType(getConnectorType())
                .electricalProperties(getElectricalProperties());
        return builder;
    }

    /**
     * Class to build instances of {@link ConnectorV2}.
     */
    public static class Builder {
        private String uid;
        private String externalId;
        private ConnectorVOConnectorTypeEnum connectorType;
        private ElectricalPropertiesV2 electricalProperties;



        /**
         * Setter for uid.
         * @param  uid  String value for uid.
         * @return Builder
         */
        public Builder uid(String uid) {
            this.uid = uid;
            return this;
        }

        /**
         * Setter for externalId.
         * @param  externalId  String value for externalId.
         * @return Builder
         */
        public Builder externalId(String externalId) {
            this.externalId = externalId;
            return this;
        }

        /**
         * Setter for connectorType.
         * @param  connectorType  ConnectorVOConnectorTypeEnum value for connectorType.
         * @return Builder
         */
        public Builder connectorType(ConnectorVOConnectorTypeEnum connectorType) {
            this.connectorType = connectorType;
            return this;
        }

        /**
         * Setter for electricalProperties.
         * @param  electricalProperties  ElectricalPropertiesV2 value for electricalProperties.
         * @return Builder
         */
        public Builder electricalProperties(ElectricalPropertiesV2 electricalProperties) {
            this.electricalProperties = electricalProperties;
            return this;
        }

        /**
         * Builds a new {@link ConnectorV2} object using the set fields.
         * @return {@link ConnectorV2}
         */
        public ConnectorV2 build() {
            return new ConnectorV2(uid, externalId, connectorType, electricalProperties);
        }
    }
}
