/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * EvseVOStatusEnum to be used.
 */
public enum EvseVOStatusEnum {
    AVAILABLE,

    OCCUPIED,

    UNAVAILABLE,

    UNKNOWN;


    private static TreeMap<String, EvseVOStatusEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        AVAILABLE.value = "Available";
        OCCUPIED.value = "Occupied";
        UNAVAILABLE.value = "Unavailable";
        UNKNOWN.value = "Unknown";

        valueMap.put("Available", AVAILABLE);
        valueMap.put("Occupied", OCCUPIED);
        valueMap.put("Unavailable", UNAVAILABLE);
        valueMap.put("Unknown", UNKNOWN);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static EvseVOStatusEnum constructFromString(String toConvert) throws IOException {
        EvseVOStatusEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static EvseVOStatusEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of EvseVOStatusEnum values to list of string values.
     * @param toConvert The list of EvseVOStatusEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<EvseVOStatusEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (EvseVOStatusEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 