/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.UUID;

/**
 * This is a model class for InlineResponse2021 type.
 */
public class InlineResponse2021 {
    private UUID requestId;
    private GetChargeSessionRetrieveResponse200JsonStatusEnum status;

    /**
     * Default constructor.
     */
    public InlineResponse2021() {
    }

    /**
     * Initialization constructor.
     * @param  requestId  UUID value for requestId.
     * @param  status  GetChargeSessionRetrieveResponse200JsonStatusEnum value for status.
     */
    public InlineResponse2021(
            UUID requestId,
            GetChargeSessionRetrieveResponse200JsonStatusEnum status) {
        this.requestId = requestId;
        this.status = status;
    }

    /**
     * Getter for RequestId.
     * Mandatory UUID (according to RFC 4122 standards) for requests and responses. This will be
     * played back in the response from the request.
     * @return Returns the UUID
     */
    @JsonGetter("requestId")
    public UUID getRequestId() {
        return requestId;
    }

    /**
     * Setter for RequestId.
     * Mandatory UUID (according to RFC 4122 standards) for requests and responses. This will be
     * played back in the response from the request.
     * @param requestId Value for UUID
     */
    @JsonSetter("requestId")
    public void setRequestId(UUID requestId) {
        this.requestId = requestId;
    }

    /**
     * Getter for Status.
     * @return Returns the GetChargeSessionRetrieveResponse200JsonStatusEnum
     */
    @JsonGetter("status")
    public GetChargeSessionRetrieveResponse200JsonStatusEnum getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for GetChargeSessionRetrieveResponse200JsonStatusEnum
     */
    @JsonSetter("status")
    public void setStatus(GetChargeSessionRetrieveResponse200JsonStatusEnum status) {
        this.status = status;
    }

    /**
     * Converts this InlineResponse2021 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InlineResponse2021 [" + "requestId=" + requestId + ", status=" + status + "]";
    }

    /**
     * Builds a new {@link InlineResponse2021.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InlineResponse2021.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(requestId, status);
        return builder;
    }

    /**
     * Class to build instances of {@link InlineResponse2021}.
     */
    public static class Builder {
        private UUID requestId;
        private GetChargeSessionRetrieveResponse200JsonStatusEnum status;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  requestId  UUID value for requestId.
         * @param  status  GetChargeSessionRetrieveResponse200JsonStatusEnum value for status.
         */
        public Builder(UUID requestId, GetChargeSessionRetrieveResponse200JsonStatusEnum status) {
            this.requestId = requestId;
            this.status = status;
        }

        /**
         * Setter for requestId.
         * @param  requestId  UUID value for requestId.
         * @return Builder
         */
        public Builder requestId(UUID requestId) {
            this.requestId = requestId;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  GetChargeSessionRetrieveResponse200JsonStatusEnum value for status.
         * @return Builder
         */
        public Builder status(GetChargeSessionRetrieveResponse200JsonStatusEnum status) {
            this.status = status;
            return this;
        }

        /**
         * Builds a new {@link InlineResponse2021} object using the set fields.
         * @return {@link InlineResponse2021}
         */
        public InlineResponse2021 build() {
            return new InlineResponse2021(requestId, status);
        }
    }
}
