/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for InternalErrorObject type.
 */
public class InternalErrorObject {
    private String code;
    private String message;
    private String description;

    /**
     * Default constructor.
     */
    public InternalErrorObject() {
    }

    /**
     * Initialization constructor.
     * @param  code  String value for code.
     * @param  message  String value for message.
     * @param  description  String value for description.
     */
    public InternalErrorObject(
            String code,
            String message,
            String description) {
        this.code = code;
        this.message = message;
        this.description = description;
    }

    /**
     * Getter for Code.
     * Error code
     * @return Returns the String
     */
    @JsonGetter("code")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCode() {
        return code;
    }

    /**
     * Setter for Code.
     * Error code
     * @param code Value for String
     */
    @JsonSetter("code")
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for Message.
     * Error description in English
     * @return Returns the String
     */
    @JsonGetter("message")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMessage() {
        return message;
    }

    /**
     * Setter for Message.
     * Error description in English
     * @param message Value for String
     */
    @JsonSetter("message")
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Getter for Description.
     * Technical details of the error message, the example which is given in the sample payload is
     * one of the scenario. actual response will vary based on the technical nature
     * @return Returns the String
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * Technical details of the error message, the example which is given in the sample payload is
     * one of the scenario. actual response will vary based on the technical nature
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Converts this InternalErrorObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InternalErrorObject [" + "code=" + code + ", message=" + message + ", description="
                + description + "]";
    }

    /**
     * Builds a new {@link InternalErrorObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InternalErrorObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .code(getCode())
                .message(getMessage())
                .description(getDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link InternalErrorObject}.
     */
    public static class Builder {
        private String code;
        private String message;
        private String description;



        /**
         * Setter for code.
         * @param  code  String value for code.
         * @return Builder
         */
        public Builder code(String code) {
            this.code = code;
            return this;
        }

        /**
         * Setter for message.
         * @param  message  String value for message.
         * @return Builder
         */
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Builds a new {@link InternalErrorObject} object using the set fields.
         * @return {@link InternalErrorObject}
         */
        public InternalErrorObject build() {
            return new InternalErrorObject(code, message, description);
        }
    }
}
