/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.api.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MultiLocationMarkerV2 type.
 */
public class MultiLocationMarkerV2 {
    private Coordinates coordinates;
    private Double locationCount;
    private Double evseCount;
    private Double maxPower;
    private String operatorName;
    private String markerType;

    /**
     * Default constructor.
     */
    public MultiLocationMarkerV2() {
        markerType = "MultiLocation";
    }

    /**
     * Initialization constructor.
     * @param  markerType  String value for markerType.
     * @param  coordinates  Coordinates value for coordinates.
     * @param  locationCount  Double value for locationCount.
     * @param  evseCount  Double value for evseCount.
     * @param  maxPower  Double value for maxPower.
     * @param  operatorName  String value for operatorName.
     */
    public MultiLocationMarkerV2(
            String markerType,
            Coordinates coordinates,
            Double locationCount,
            Double evseCount,
            Double maxPower,
            String operatorName) {
        this.coordinates = coordinates;
        this.locationCount = locationCount;
        this.evseCount = evseCount;
        this.maxPower = maxPower;
        this.operatorName = operatorName;
        this.markerType = markerType;
    }

    /**
     * Initialization constructor.
     * @param  markerType  String value for markerType.
     */
    @JsonCreator
    protected MultiLocationMarkerV2(
            @JsonProperty("markerType") String markerType) {
        this(markerType, null, null, null, null, null);
    }

    /**
     * Getter for Coordinates.
     * Coordinates of the Shell Recharge Site Location
     * @return Returns the Coordinates
     */
    @JsonGetter("coordinates")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Coordinates getCoordinates() {
        return coordinates;
    }

    /**
     * Setter for Coordinates.
     * Coordinates of the Shell Recharge Site Location
     * @param coordinates Value for Coordinates
     */
    @JsonSetter("coordinates")
    public void setCoordinates(Coordinates coordinates) {
        this.coordinates = coordinates;
    }

    /**
     * Getter for LocationCount.
     * Number of Locations that this Marker represents in the given set of bounds
     * @return Returns the Double
     */
    @JsonGetter("locationCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getLocationCount() {
        return locationCount;
    }

    /**
     * Setter for LocationCount.
     * Number of Locations that this Marker represents in the given set of bounds
     * @param locationCount Value for Double
     */
    @JsonSetter("locationCount")
    public void setLocationCount(Double locationCount) {
        this.locationCount = locationCount;
    }

    /**
     * Getter for EvseCount.
     * Total number of Evses in Locations that this Marker represents
     * @return Returns the Double
     */
    @JsonGetter("evseCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getEvseCount() {
        return evseCount;
    }

    /**
     * Setter for EvseCount.
     * Total number of Evses in Locations that this Marker represents
     * @param evseCount Value for Double
     */
    @JsonSetter("evseCount")
    public void setEvseCount(Double evseCount) {
        this.evseCount = evseCount;
    }

    /**
     * Getter for MaxPower.
     * Maximum power in kW across all locations grouped in this marker (disregarding availability)
     * @return Returns the Double
     */
    @JsonGetter("maxPower")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getMaxPower() {
        return maxPower;
    }

    /**
     * Setter for MaxPower.
     * Maximum power in kW across all locations grouped in this marker (disregarding availability)
     * @param maxPower Value for Double
     */
    @JsonSetter("maxPower")
    public void setMaxPower(Double maxPower) {
        this.maxPower = maxPower;
    }

    /**
     * Getter for OperatorName.
     * Operator of this Shell Recharge Location
     * @return Returns the String
     */
    @JsonGetter("operatorName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * Setter for OperatorName.
     * Operator of this Shell Recharge Location
     * @param operatorName Value for String
     */
    @JsonSetter("operatorName")
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName;
    }

    /**
     * Getter for MarkerType.
     * Type of the Marker, in this case it will always be MultiLocation
     * @return Returns the String
     */
    @JsonGetter("markerType")
    public String getMarkerType() {
        return markerType;
    }

    /**
     * Setter for MarkerType.
     * Type of the Marker, in this case it will always be MultiLocation
     * @param markerType Value for String
     */
    @JsonSetter("markerType")
    private void setMarkerType(String markerType) {
        this.markerType = markerType;
    }

    /**
     * Converts this MultiLocationMarkerV2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MultiLocationMarkerV2 [" + "markerType=" + markerType + ", coordinates="
                + coordinates + ", locationCount=" + locationCount + ", evseCount=" + evseCount
                + ", maxPower=" + maxPower + ", operatorName=" + operatorName + "]";
    }

    /**
     * Builds a new {@link MultiLocationMarkerV2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MultiLocationMarkerV2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(markerType)
                .coordinates(getCoordinates())
                .locationCount(getLocationCount())
                .evseCount(getEvseCount())
                .maxPower(getMaxPower())
                .operatorName(getOperatorName());
        return builder;
    }

    /**
     * Class to build instances of {@link MultiLocationMarkerV2}.
     */
    public static class Builder {
        private String markerType = "MultiLocation";
        private Coordinates coordinates;
        private Double locationCount;
        private Double evseCount;
        private Double maxPower;
        private String operatorName;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  markerType  String value for markerType.
         */
        public Builder(String markerType) {
            this.markerType = markerType;
        }

        /**
         * Setter for markerType.
         * @param  markerType  String value for markerType.
         * @return Builder
         */
        public Builder markerType(String markerType) {
            this.markerType = markerType;
            return this;
        }

        /**
         * Setter for coordinates.
         * @param  coordinates  Coordinates value for coordinates.
         * @return Builder
         */
        public Builder coordinates(Coordinates coordinates) {
            this.coordinates = coordinates;
            return this;
        }

        /**
         * Setter for locationCount.
         * @param  locationCount  Double value for locationCount.
         * @return Builder
         */
        public Builder locationCount(Double locationCount) {
            this.locationCount = locationCount;
            return this;
        }

        /**
         * Setter for evseCount.
         * @param  evseCount  Double value for evseCount.
         * @return Builder
         */
        public Builder evseCount(Double evseCount) {
            this.evseCount = evseCount;
            return this;
        }

        /**
         * Setter for maxPower.
         * @param  maxPower  Double value for maxPower.
         * @return Builder
         */
        public Builder maxPower(Double maxPower) {
            this.maxPower = maxPower;
            return this;
        }

        /**
         * Setter for operatorName.
         * @param  operatorName  String value for operatorName.
         * @return Builder
         */
        public Builder operatorName(String operatorName) {
            this.operatorName = operatorName;
            return this;
        }

        /**
         * Builds a new {@link MultiLocationMarkerV2} object using the set fields.
         * @return {@link MultiLocationMarkerV2}
         */
        public MultiLocationMarkerV2 build() {
            return new MultiLocationMarkerV2(markerType, coordinates, locationCount, evseCount,
                    maxPower, operatorName);
        }
    }
}
