/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for OpeningHoursObject type.
 */
public class OpeningHoursObject {
    private OpeningHoursObjectWeekDayEnum weekDay;
    private String startTime;
    private String endTime;

    /**
     * Default constructor.
     */
    public OpeningHoursObject() {
    }

    /**
     * Initialization constructor.
     * @param  weekDay  OpeningHoursObjectWeekDayEnum value for weekDay.
     * @param  startTime  String value for startTime.
     * @param  endTime  String value for endTime.
     */
    public OpeningHoursObject(
            OpeningHoursObjectWeekDayEnum weekDay,
            String startTime,
            String endTime) {
        this.weekDay = weekDay;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    /**
     * Getter for WeekDay.
     * @return Returns the OpeningHoursObjectWeekDayEnum
     */
    @JsonGetter("weekDay")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public OpeningHoursObjectWeekDayEnum getWeekDay() {
        return weekDay;
    }

    /**
     * Setter for WeekDay.
     * @param weekDay Value for OpeningHoursObjectWeekDayEnum
     */
    @JsonSetter("weekDay")
    public void setWeekDay(OpeningHoursObjectWeekDayEnum weekDay) {
        this.weekDay = weekDay;
    }

    /**
     * Getter for StartTime.
     * Hour in 24h local time when the location opens.
     * @return Returns the String
     */
    @JsonGetter("startTime")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStartTime() {
        return startTime;
    }

    /**
     * Setter for StartTime.
     * Hour in 24h local time when the location opens.
     * @param startTime Value for String
     */
    @JsonSetter("startTime")
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * Getter for EndTime.
     * Hour in 24h local time when the location closes.
     * @return Returns the String
     */
    @JsonGetter("endTime")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getEndTime() {
        return endTime;
    }

    /**
     * Setter for EndTime.
     * Hour in 24h local time when the location closes.
     * @param endTime Value for String
     */
    @JsonSetter("endTime")
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * Converts this OpeningHoursObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "OpeningHoursObject [" + "weekDay=" + weekDay + ", startTime=" + startTime
                + ", endTime=" + endTime + "]";
    }

    /**
     * Builds a new {@link OpeningHoursObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link OpeningHoursObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .weekDay(getWeekDay())
                .startTime(getStartTime())
                .endTime(getEndTime());
        return builder;
    }

    /**
     * Class to build instances of {@link OpeningHoursObject}.
     */
    public static class Builder {
        private OpeningHoursObjectWeekDayEnum weekDay;
        private String startTime;
        private String endTime;



        /**
         * Setter for weekDay.
         * @param  weekDay  OpeningHoursObjectWeekDayEnum value for weekDay.
         * @return Builder
         */
        public Builder weekDay(OpeningHoursObjectWeekDayEnum weekDay) {
            this.weekDay = weekDay;
            return this;
        }

        /**
         * Setter for startTime.
         * @param  startTime  String value for startTime.
         * @return Builder
         */
        public Builder startTime(String startTime) {
            this.startTime = startTime;
            return this;
        }

        /**
         * Setter for endTime.
         * @param  endTime  String value for endTime.
         * @return Builder
         */
        public Builder endTime(String endTime) {
            this.endTime = endTime;
            return this;
        }

        /**
         * Builds a new {@link OpeningHoursObject} object using the set fields.
         * @return {@link OpeningHoursObject}
         */
        public OpeningHoursObject build() {
            return new OpeningHoursObject(weekDay, startTime, endTime);
        }
    }
}
