/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PowerRange type.
 */
public class PowerRange {
    private int min;
    private int max;

    /**
     * Default constructor.
     */
    public PowerRange() {
    }

    /**
     * Initialization constructor.
     * @param  min  int value for min.
     * @param  max  int value for max.
     */
    public PowerRange(
            int min,
            int max) {
        this.min = min;
        this.max = max;
    }

    /**
     * Getter for Min.
     * Minimum supported power in kW
     * @return Returns the int
     */
    @JsonGetter("min")
    public int getMin() {
        return min;
    }

    /**
     * Setter for Min.
     * Minimum supported power in kW
     * @param min Value for int
     */
    @JsonSetter("min")
    public void setMin(int min) {
        this.min = min;
    }

    /**
     * Getter for Max.
     * Maximum supported power in kW
     * @return Returns the int
     */
    @JsonGetter("max")
    public int getMax() {
        return max;
    }

    /**
     * Setter for Max.
     * Maximum supported power in kW
     * @param max Value for int
     */
    @JsonSetter("max")
    public void setMax(int max) {
        this.max = max;
    }

    /**
     * Converts this PowerRange into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PowerRange [" + "min=" + min + ", max=" + max + "]";
    }

    /**
     * Builds a new {@link PowerRange.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PowerRange.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(min, max);
        return builder;
    }

    /**
     * Class to build instances of {@link PowerRange}.
     */
    public static class Builder {
        private int min;
        private int max;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  min  int value for min.
         * @param  max  int value for max.
         */
        public Builder(int min, int max) {
            this.min = min;
            this.max = max;
        }

        /**
         * Setter for min.
         * @param  min  int value for min.
         * @return Builder
         */
        public Builder min(int min) {
            this.min = min;
            return this;
        }

        /**
         * Setter for max.
         * @param  max  int value for max.
         * @return Builder
         */
        public Builder max(int max) {
            this.max = max;
            return this;
        }

        /**
         * Builds a new {@link PowerRange} object using the set fields.
         * @return {@link PowerRange}
         */
        public PowerRange build() {
            return new PowerRange(min, max);
        }
    }
}
