/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import java.util.UUID;

/**
 * This is a model class for ResponseV2 type.
 */
public class ResponseV2 {
    private UUID requestId;
    private String status;
    private List<LocationResponeObjectV2> data;

    /**
     * Default constructor.
     */
    public ResponseV2() {
    }

    /**
     * Initialization constructor.
     * @param  requestId  UUID value for requestId.
     * @param  status  String value for status.
     * @param  data  List of LocationResponeObjectV2 value for data.
     */
    public ResponseV2(
            UUID requestId,
            String status,
            List<LocationResponeObjectV2> data) {
        this.requestId = requestId;
        this.status = status;
        this.data = data;
    }

    /**
     * Getter for RequestId.
     * requestId is unique identifier value that is attached to requests and messages that allow
     * reference to a particular transaction or event chain.
     * @return Returns the UUID
     */
    @JsonGetter("requestId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UUID getRequestId() {
        return requestId;
    }

    /**
     * Setter for RequestId.
     * requestId is unique identifier value that is attached to requests and messages that allow
     * reference to a particular transaction or event chain.
     * @param requestId Value for UUID
     */
    @JsonSetter("requestId")
    public void setRequestId(UUID requestId) {
        this.requestId = requestId;
    }

    /**
     * Getter for Status.
     * status of the API call
     * @return Returns the String
     */
    @JsonGetter("status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * status of the API call
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for Data.
     * API Response
     * @return Returns the List of LocationResponeObjectV2
     */
    @JsonGetter("data")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<LocationResponeObjectV2> getData() {
        return data;
    }

    /**
     * Setter for Data.
     * API Response
     * @param data Value for List of LocationResponeObjectV2
     */
    @JsonSetter("data")
    public void setData(List<LocationResponeObjectV2> data) {
        this.data = data;
    }

    /**
     * Converts this ResponseV2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ResponseV2 [" + "requestId=" + requestId + ", status=" + status + ", data=" + data
                + "]";
    }

    /**
     * Builds a new {@link ResponseV2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ResponseV2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .requestId(getRequestId())
                .status(getStatus())
                .data(getData());
        return builder;
    }

    /**
     * Class to build instances of {@link ResponseV2}.
     */
    public static class Builder {
        private UUID requestId;
        private String status;
        private List<LocationResponeObjectV2> data;



        /**
         * Setter for requestId.
         * @param  requestId  UUID value for requestId.
         * @return Builder
         */
        public Builder requestId(UUID requestId) {
            this.requestId = requestId;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for data.
         * @param  data  List of LocationResponeObjectV2 value for data.
         * @return Builder
         */
        public Builder data(List<LocationResponeObjectV2> data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link ResponseV2} object using the set fields.
         * @return {@link ResponseV2}
         */
        public ResponseV2 build() {
            return new ResponseV2(requestId, status, data);
        }
    }
}
