/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.shell.api.DateTimeHelper;
import java.time.LocalDate;
import java.util.List;

/**
 * This is a model class for Restrictions type.
 */
public class Restrictions {
    private String startTime;
    private String endTime;
    private LocalDate startDate;
    private LocalDate endDate;
    private Double minKwh;
    private Double maxKwh;
    private Double minCurrent;
    private Double maxCurrent;
    private Double minPower;
    private Double maxPower;
    private Integer minDuration;
    private Integer maxDuration;
    private List<DayOfWeekEnum> dayOfWeek;

    /**
     * Default constructor.
     */
    public Restrictions() {
    }

    /**
     * Initialization constructor.
     * @param  startTime  String value for startTime.
     * @param  endTime  String value for endTime.
     * @param  startDate  LocalDate value for startDate.
     * @param  endDate  LocalDate value for endDate.
     * @param  minKwh  Double value for minKwh.
     * @param  maxKwh  Double value for maxKwh.
     * @param  minCurrent  Double value for minCurrent.
     * @param  maxCurrent  Double value for maxCurrent.
     * @param  minPower  Double value for minPower.
     * @param  maxPower  Double value for maxPower.
     * @param  minDuration  Integer value for minDuration.
     * @param  maxDuration  Integer value for maxDuration.
     * @param  dayOfWeek  List of DayOfWeekEnum value for dayOfWeek.
     */
    public Restrictions(
            String startTime,
            String endTime,
            LocalDate startDate,
            LocalDate endDate,
            Double minKwh,
            Double maxKwh,
            Double minCurrent,
            Double maxCurrent,
            Double minPower,
            Double maxPower,
            Integer minDuration,
            Integer maxDuration,
            List<DayOfWeekEnum> dayOfWeek) {
        this.startTime = startTime;
        this.endTime = endTime;
        this.startDate = startDate;
        this.endDate = endDate;
        this.minKwh = minKwh;
        this.maxKwh = maxKwh;
        this.minCurrent = minCurrent;
        this.maxCurrent = maxCurrent;
        this.minPower = minPower;
        this.maxPower = maxPower;
        this.minDuration = minDuration;
        this.maxDuration = maxDuration;
        this.dayOfWeek = dayOfWeek;
    }

    /**
     * Getter for StartTime.
     * Valid from this time of the day (HH:mm)
     * @return Returns the String
     */
    @JsonGetter("startTime")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStartTime() {
        return startTime;
    }

    /**
     * Setter for StartTime.
     * Valid from this time of the day (HH:mm)
     * @param startTime Value for String
     */
    @JsonSetter("startTime")
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * Getter for EndTime.
     * Valid until this time of the day (HH:mm)
     * @return Returns the String
     */
    @JsonGetter("endTime")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getEndTime() {
        return endTime;
    }

    /**
     * Setter for EndTime.
     * Valid until this time of the day (HH:mm)
     * @param endTime Value for String
     */
    @JsonSetter("endTime")
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * Getter for StartDate.
     * @return Returns the LocalDate
     */
    @JsonGetter("startDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getStartDate() {
        return startDate;
    }

    /**
     * Setter for StartDate.
     * @param startDate Value for LocalDate
     */
    @JsonSetter("startDate")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    /**
     * Getter for EndDate.
     * @return Returns the LocalDate
     */
    @JsonGetter("endDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getEndDate() {
        return endDate;
    }

    /**
     * Setter for EndDate.
     * @param endDate Value for LocalDate
     */
    @JsonSetter("endDate")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    /**
     * Getter for MinKwh.
     * @return Returns the Double
     */
    @JsonGetter("minKwh")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getMinKwh() {
        return minKwh;
    }

    /**
     * Setter for MinKwh.
     * @param minKwh Value for Double
     */
    @JsonSetter("minKwh")
    public void setMinKwh(Double minKwh) {
        this.minKwh = minKwh;
    }

    /**
     * Getter for MaxKwh.
     * @return Returns the Double
     */
    @JsonGetter("maxKwh")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getMaxKwh() {
        return maxKwh;
    }

    /**
     * Setter for MaxKwh.
     * @param maxKwh Value for Double
     */
    @JsonSetter("maxKwh")
    public void setMaxKwh(Double maxKwh) {
        this.maxKwh = maxKwh;
    }

    /**
     * Getter for MinCurrent.
     * @return Returns the Double
     */
    @JsonGetter("minCurrent")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getMinCurrent() {
        return minCurrent;
    }

    /**
     * Setter for MinCurrent.
     * @param minCurrent Value for Double
     */
    @JsonSetter("minCurrent")
    public void setMinCurrent(Double minCurrent) {
        this.minCurrent = minCurrent;
    }

    /**
     * Getter for MaxCurrent.
     * @return Returns the Double
     */
    @JsonGetter("maxCurrent")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getMaxCurrent() {
        return maxCurrent;
    }

    /**
     * Setter for MaxCurrent.
     * @param maxCurrent Value for Double
     */
    @JsonSetter("maxCurrent")
    public void setMaxCurrent(Double maxCurrent) {
        this.maxCurrent = maxCurrent;
    }

    /**
     * Getter for MinPower.
     * @return Returns the Double
     */
    @JsonGetter("minPower")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getMinPower() {
        return minPower;
    }

    /**
     * Setter for MinPower.
     * @param minPower Value for Double
     */
    @JsonSetter("minPower")
    public void setMinPower(Double minPower) {
        this.minPower = minPower;
    }

    /**
     * Getter for MaxPower.
     * @return Returns the Double
     */
    @JsonGetter("maxPower")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getMaxPower() {
        return maxPower;
    }

    /**
     * Setter for MaxPower.
     * @param maxPower Value for Double
     */
    @JsonSetter("maxPower")
    public void setMaxPower(Double maxPower) {
        this.maxPower = maxPower;
    }

    /**
     * Getter for MinDuration.
     * Minimum session duration in seconds
     * @return Returns the Integer
     */
    @JsonGetter("minDuration")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getMinDuration() {
        return minDuration;
    }

    /**
     * Setter for MinDuration.
     * Minimum session duration in seconds
     * @param minDuration Value for Integer
     */
    @JsonSetter("minDuration")
    public void setMinDuration(Integer minDuration) {
        this.minDuration = minDuration;
    }

    /**
     * Getter for MaxDuration.
     * Maximum session duration in seconds
     * @return Returns the Integer
     */
    @JsonGetter("maxDuration")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getMaxDuration() {
        return maxDuration;
    }

    /**
     * Setter for MaxDuration.
     * Maximum session duration in seconds
     * @param maxDuration Value for Integer
     */
    @JsonSetter("maxDuration")
    public void setMaxDuration(Integer maxDuration) {
        this.maxDuration = maxDuration;
    }

    /**
     * Getter for DayOfWeek.
     * @return Returns the List of DayOfWeekEnum
     */
    @JsonGetter("dayOfWeek")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<DayOfWeekEnum> getDayOfWeek() {
        return dayOfWeek;
    }

    /**
     * Setter for DayOfWeek.
     * @param dayOfWeek Value for List of DayOfWeekEnum
     */
    @JsonSetter("dayOfWeek")
    public void setDayOfWeek(List<DayOfWeekEnum> dayOfWeek) {
        this.dayOfWeek = dayOfWeek;
    }

    /**
     * Converts this Restrictions into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Restrictions [" + "startTime=" + startTime + ", endTime=" + endTime + ", startDate="
                + startDate + ", endDate=" + endDate + ", minKwh=" + minKwh + ", maxKwh=" + maxKwh
                + ", minCurrent=" + minCurrent + ", maxCurrent=" + maxCurrent + ", minPower="
                + minPower + ", maxPower=" + maxPower + ", minDuration=" + minDuration
                + ", maxDuration=" + maxDuration + ", dayOfWeek=" + dayOfWeek + "]";
    }

    /**
     * Builds a new {@link Restrictions.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Restrictions.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .startTime(getStartTime())
                .endTime(getEndTime())
                .startDate(getStartDate())
                .endDate(getEndDate())
                .minKwh(getMinKwh())
                .maxKwh(getMaxKwh())
                .minCurrent(getMinCurrent())
                .maxCurrent(getMaxCurrent())
                .minPower(getMinPower())
                .maxPower(getMaxPower())
                .minDuration(getMinDuration())
                .maxDuration(getMaxDuration())
                .dayOfWeek(getDayOfWeek());
        return builder;
    }

    /**
     * Class to build instances of {@link Restrictions}.
     */
    public static class Builder {
        private String startTime;
        private String endTime;
        private LocalDate startDate;
        private LocalDate endDate;
        private Double minKwh;
        private Double maxKwh;
        private Double minCurrent;
        private Double maxCurrent;
        private Double minPower;
        private Double maxPower;
        private Integer minDuration;
        private Integer maxDuration;
        private List<DayOfWeekEnum> dayOfWeek;



        /**
         * Setter for startTime.
         * @param  startTime  String value for startTime.
         * @return Builder
         */
        public Builder startTime(String startTime) {
            this.startTime = startTime;
            return this;
        }

        /**
         * Setter for endTime.
         * @param  endTime  String value for endTime.
         * @return Builder
         */
        public Builder endTime(String endTime) {
            this.endTime = endTime;
            return this;
        }

        /**
         * Setter for startDate.
         * @param  startDate  LocalDate value for startDate.
         * @return Builder
         */
        public Builder startDate(LocalDate startDate) {
            this.startDate = startDate;
            return this;
        }

        /**
         * Setter for endDate.
         * @param  endDate  LocalDate value for endDate.
         * @return Builder
         */
        public Builder endDate(LocalDate endDate) {
            this.endDate = endDate;
            return this;
        }

        /**
         * Setter for minKwh.
         * @param  minKwh  Double value for minKwh.
         * @return Builder
         */
        public Builder minKwh(Double minKwh) {
            this.minKwh = minKwh;
            return this;
        }

        /**
         * Setter for maxKwh.
         * @param  maxKwh  Double value for maxKwh.
         * @return Builder
         */
        public Builder maxKwh(Double maxKwh) {
            this.maxKwh = maxKwh;
            return this;
        }

        /**
         * Setter for minCurrent.
         * @param  minCurrent  Double value for minCurrent.
         * @return Builder
         */
        public Builder minCurrent(Double minCurrent) {
            this.minCurrent = minCurrent;
            return this;
        }

        /**
         * Setter for maxCurrent.
         * @param  maxCurrent  Double value for maxCurrent.
         * @return Builder
         */
        public Builder maxCurrent(Double maxCurrent) {
            this.maxCurrent = maxCurrent;
            return this;
        }

        /**
         * Setter for minPower.
         * @param  minPower  Double value for minPower.
         * @return Builder
         */
        public Builder minPower(Double minPower) {
            this.minPower = minPower;
            return this;
        }

        /**
         * Setter for maxPower.
         * @param  maxPower  Double value for maxPower.
         * @return Builder
         */
        public Builder maxPower(Double maxPower) {
            this.maxPower = maxPower;
            return this;
        }

        /**
         * Setter for minDuration.
         * @param  minDuration  Integer value for minDuration.
         * @return Builder
         */
        public Builder minDuration(Integer minDuration) {
            this.minDuration = minDuration;
            return this;
        }

        /**
         * Setter for maxDuration.
         * @param  maxDuration  Integer value for maxDuration.
         * @return Builder
         */
        public Builder maxDuration(Integer maxDuration) {
            this.maxDuration = maxDuration;
            return this;
        }

        /**
         * Setter for dayOfWeek.
         * @param  dayOfWeek  List of DayOfWeekEnum value for dayOfWeek.
         * @return Builder
         */
        public Builder dayOfWeek(List<DayOfWeekEnum> dayOfWeek) {
            this.dayOfWeek = dayOfWeek;
            return this;
        }

        /**
         * Builds a new {@link Restrictions} object using the set fields.
         * @return {@link Restrictions}
         */
        public Restrictions build() {
            return new Restrictions(startTime, endTime, startDate, endDate, minKwh, maxKwh,
                    minCurrent, maxCurrent, minPower, maxPower, minDuration, maxDuration,
                    dayOfWeek);
        }
    }
}
