/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for TariffAltText type.
 */
public class TariffAltText {
    private String language;
    private String text;

    /**
     * Default constructor.
     */
    public TariffAltText() {
    }

    /**
     * Initialization constructor.
     * @param  language  String value for language.
     * @param  text  String value for text.
     */
    public TariffAltText(
            String language,
            String text) {
        this.language = language;
        this.text = text;
    }

    /**
     * Getter for Language.
     * ISO language code
     * @return Returns the String
     */
    @JsonGetter("language")
    public String getLanguage() {
        return language;
    }

    /**
     * Setter for Language.
     * ISO language code
     * @param language Value for String
     */
    @JsonSetter("language")
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * Getter for Text.
     * Human readable tariff description
     * @return Returns the String
     */
    @JsonGetter("text")
    public String getText() {
        return text;
    }

    /**
     * Setter for Text.
     * Human readable tariff description
     * @param text Value for String
     */
    @JsonSetter("text")
    public void setText(String text) {
        this.text = text;
    }

    /**
     * Converts this TariffAltText into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TariffAltText [" + "language=" + language + ", text=" + text + "]";
    }

    /**
     * Builds a new {@link TariffAltText.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TariffAltText.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(language, text);
        return builder;
    }

    /**
     * Class to build instances of {@link TariffAltText}.
     */
    public static class Builder {
        private String language;
        private String text;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  language  String value for language.
         * @param  text  String value for text.
         */
        public Builder(String language, String text) {
            this.language = language;
            this.text = text;
        }

        /**
         * Setter for language.
         * @param  language  String value for language.
         * @return Builder
         */
        public Builder language(String language) {
            this.language = language;
            return this;
        }

        /**
         * Setter for text.
         * @param  text  String value for text.
         * @return Builder
         */
        public Builder text(String text) {
            this.text = text;
            return this;
        }

        /**
         * Builds a new {@link TariffAltText} object using the set fields.
         * @return {@link TariffAltText}
         */
        public TariffAltText build() {
            return new TariffAltText(language, text);
        }
    }
}
