/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Tariff type.
 */
public class Tariff {
    private Double startFee;
    private Double perMinute;
    private Double perKWh;
    private String currency;
    private String updated;
    private TariffVOUpdatedByEnum updatedBy;
    private String structure;

    /**
     * Default constructor.
     */
    public Tariff() {
    }

    /**
     * Initialization constructor.
     * @param  startFee  Double value for startFee.
     * @param  perMinute  Double value for perMinute.
     * @param  perKWh  Double value for perKWh.
     * @param  currency  String value for currency.
     * @param  updated  String value for updated.
     * @param  updatedBy  TariffVOUpdatedByEnum value for updatedBy.
     * @param  structure  String value for structure.
     */
    public Tariff(
            Double startFee,
            Double perMinute,
            Double perKWh,
            String currency,
            String updated,
            TariffVOUpdatedByEnum updatedBy,
            String structure) {
        this.startFee = startFee;
        this.perMinute = perMinute;
        this.perKWh = perKWh;
        this.currency = currency;
        this.updated = updated;
        this.updatedBy = updatedBy;
        this.structure = structure;
    }

    /**
     * Getter for StartFee.
     * Tariff to start a charging session
     * @return Returns the Double
     */
    @JsonGetter("startFee")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getStartFee() {
        return startFee;
    }

    /**
     * Setter for StartFee.
     * Tariff to start a charging session
     * @param startFee Value for Double
     */
    @JsonSetter("startFee")
    public void setStartFee(Double startFee) {
        this.startFee = startFee;
    }

    /**
     * Getter for PerMinute.
     * Tariff per minute of charging time
     * @return Returns the Double
     */
    @JsonGetter("perMinute")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getPerMinute() {
        return perMinute;
    }

    /**
     * Setter for PerMinute.
     * Tariff per minute of charging time
     * @param perMinute Value for Double
     */
    @JsonSetter("perMinute")
    public void setPerMinute(Double perMinute) {
        this.perMinute = perMinute;
    }

    /**
     * Getter for PerKWh.
     * Tariff per kWh of energy consumed
     * @return Returns the Double
     */
    @JsonGetter("perKWh")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getPerKWh() {
        return perKWh;
    }

    /**
     * Setter for PerKWh.
     * Tariff per kWh of energy consumed
     * @param perKWh Value for Double
     */
    @JsonSetter("perKWh")
    public void setPerKWh(Double perKWh) {
        this.perKWh = perKWh;
    }

    /**
     * Getter for Currency.
     * ISO 4217 Currency Code of the local currency.
     * @return Returns the String
     */
    @JsonGetter("currency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCurrency() {
        return currency;
    }

    /**
     * Setter for Currency.
     * ISO 4217 Currency Code of the local currency.
     * @param currency Value for String
     */
    @JsonSetter("currency")
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * Getter for Updated.
     * ISO8601-compliant UTC datetime of the last update of the Tariff
     * @return Returns the String
     */
    @JsonGetter("updated")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUpdated() {
        return updated;
    }

    /**
     * Setter for Updated.
     * ISO8601-compliant UTC datetime of the last update of the Tariff
     * @param updated Value for String
     */
    @JsonSetter("updated")
    public void setUpdated(String updated) {
        this.updated = updated;
    }

    /**
     * Getter for UpdatedBy.
     * @return Returns the TariffVOUpdatedByEnum
     */
    @JsonGetter("updatedBy")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TariffVOUpdatedByEnum getUpdatedBy() {
        return updatedBy;
    }

    /**
     * Setter for UpdatedBy.
     * @param updatedBy Value for TariffVOUpdatedByEnum
     */
    @JsonSetter("updatedBy")
    public void setUpdatedBy(TariffVOUpdatedByEnum updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * Getter for Structure.
     * Tariff structure that this tariff belongs to, typically Default unless specific tariff is
     * defined for provider
     * @return Returns the String
     */
    @JsonGetter("structure")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStructure() {
        return structure;
    }

    /**
     * Setter for Structure.
     * Tariff structure that this tariff belongs to, typically Default unless specific tariff is
     * defined for provider
     * @param structure Value for String
     */
    @JsonSetter("structure")
    public void setStructure(String structure) {
        this.structure = structure;
    }

    /**
     * Converts this Tariff into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Tariff [" + "startFee=" + startFee + ", perMinute=" + perMinute + ", perKWh="
                + perKWh + ", currency=" + currency + ", updated=" + updated + ", updatedBy="
                + updatedBy + ", structure=" + structure + "]";
    }

    /**
     * Builds a new {@link Tariff.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Tariff.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .startFee(getStartFee())
                .perMinute(getPerMinute())
                .perKWh(getPerKWh())
                .currency(getCurrency())
                .updated(getUpdated())
                .updatedBy(getUpdatedBy())
                .structure(getStructure());
        return builder;
    }

    /**
     * Class to build instances of {@link Tariff}.
     */
    public static class Builder {
        private Double startFee;
        private Double perMinute;
        private Double perKWh;
        private String currency;
        private String updated;
        private TariffVOUpdatedByEnum updatedBy;
        private String structure;



        /**
         * Setter for startFee.
         * @param  startFee  Double value for startFee.
         * @return Builder
         */
        public Builder startFee(Double startFee) {
            this.startFee = startFee;
            return this;
        }

        /**
         * Setter for perMinute.
         * @param  perMinute  Double value for perMinute.
         * @return Builder
         */
        public Builder perMinute(Double perMinute) {
            this.perMinute = perMinute;
            return this;
        }

        /**
         * Setter for perKWh.
         * @param  perKWh  Double value for perKWh.
         * @return Builder
         */
        public Builder perKWh(Double perKWh) {
            this.perKWh = perKWh;
            return this;
        }

        /**
         * Setter for currency.
         * @param  currency  String value for currency.
         * @return Builder
         */
        public Builder currency(String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * Setter for updated.
         * @param  updated  String value for updated.
         * @return Builder
         */
        public Builder updated(String updated) {
            this.updated = updated;
            return this;
        }

        /**
         * Setter for updatedBy.
         * @param  updatedBy  TariffVOUpdatedByEnum value for updatedBy.
         * @return Builder
         */
        public Builder updatedBy(TariffVOUpdatedByEnum updatedBy) {
            this.updatedBy = updatedBy;
            return this;
        }

        /**
         * Setter for structure.
         * @param  structure  String value for structure.
         * @return Builder
         */
        public Builder structure(String structure) {
            this.structure = structure;
            return this;
        }

        /**
         * Builds a new {@link Tariff} object using the set fields.
         * @return {@link Tariff}
         */
        public Tariff build() {
            return new Tariff(startFee, perMinute, perKWh, currency, updated, updatedBy, structure);
        }
    }
}
