/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * TariffTypeEnum to be used.
 */
public enum TariffTypeEnum {
    DRIVER,

    ROAMING,

    REIMBURSEMENT,

    VMSP;


    private static TreeMap<String, TariffTypeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        DRIVER.value = "DRIVER";
        ROAMING.value = "ROAMING";
        REIMBURSEMENT.value = "REIMBURSEMENT";
        VMSP.value = "VMSP";

        valueMap.put("DRIVER", DRIVER);
        valueMap.put("ROAMING", ROAMING);
        valueMap.put("REIMBURSEMENT", REIMBURSEMENT);
        valueMap.put("VMSP", VMSP);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static TariffTypeEnum constructFromString(String toConvert) throws IOException {
        TariffTypeEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static TariffTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of TariffTypeEnum values to list of string values.
     * @param toConvert The list of TariffTypeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<TariffTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (TariffTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 