/*
 * ShellEVLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.shell.apitest.models.M405ErrorResponseError;
import io.apimatic.coreinterfaces.http.Context;
import java.util.List;

/**
 * This is a model class for M405ErrorResponseError1Exception type.
 */
public class M405ErrorResponseError1Exception extends ApiException {
    private static final long serialVersionUID = -8253078918227262510L;
    private String requestId;
    private String status;
    private List<M405ErrorResponseError> errors;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public M405ErrorResponseError1Exception(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for RequestId.
     * Mandatory UUID (according to RFC 4122 standards) for requests and responses. This will be
     * played back in the response from the request.
     * @return Returns the String
     */
    @JsonGetter("RequestId")
    public String getRequestId() {
        return this.requestId;
    }

    /**
     * Setter for RequestId.
     * Mandatory UUID (according to RFC 4122 standards) for requests and responses. This will be
     * played back in the response from the request.
     * @param requestId Value for String
     */
    @JsonSetter("RequestId")
    private void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    /**
     * Getter for Status.
     * Indicates overall status of the request
     * @return Returns the String
     */
    @JsonGetter("Status")
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for Status.
     * Indicates overall status of the request
     * @param status Value for String
     */
    @JsonSetter("Status")
    private void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for Errors.
     * @return Returns the List of M405ErrorResponseError
     */
    @JsonGetter("Errors")
    public List<M405ErrorResponseError> getErrors() {
        return this.errors;
    }

    /**
     * Setter for Errors.
     * @param errors Value for List of M405ErrorResponseError
     */
    @JsonSetter("Errors")
    private void setErrors(List<M405ErrorResponseError> errors) {
        this.errors = errors;
    }
}
